### ISSUE TITLE
== BUG LIST - JULY 2018 == 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1671]
### Please link to the PR by adding the URL next to the issue or comment on this thread so that we can tip.

**Email**
- [ ] [Users Not Receiving Tips Email Notification or Profile drop down](https://github.com/gitcoinco/web/issues/1870)

**Work Schemes**
- [x] [Coop Bounty Work Started - 1 Worker Not Showing](https://github.com/gitcoinco/web/issues/1678)

**Funder Actions**
- [x] [Gitcoin Bot Should Display Value when Issue is Funded](https://github.com/gitcoinco/web/issues/1771) 
- [x] [Title and Description Not Displaying in Funder Form](https://github.com/gitcoinco/web/issues/1772)
- [x] [Disable form editing on Gitcoin ](https://github.com/gitcoinco/web/issues/1588)
- [ ] [Wrong funded time period shown](https://github.com/gitcoinco/web/issues/1774)
- [x] [ Misaligned css on gas acceptance page](https://github.com/gitcoinco/web/issues/1665)
- [x]  [Cannot approve work ](https://github.com/gitcoinco/web/issues/1537)
- [x] [Error alerts should convey a problem](https://github.com/gitcoinco/web/issues/1692)
- [ ] [Single Payout Broken](https://github.com/gitcoinco/web/issues/1859)

**Contributor Actoins**
- [x] [Too Many Alert Messages Shown](https://github.com/gitcoinco/web/issues/1792)
- [ ] [Start Work Form - Clear form field when user starts typing](https://github.com/gitcoinco/web/issues/1852)

**Landing Page**
- [x] [Inactive Back button on Contributor and Funder Ftux](https://github.com/gitcoinco/web/issues/1685)
- [x] [Button Text Not Legible](https://github.com/gitcoinco/web/issues/1686)

**Issue Explorer**
- [x] [Gas price showing as separate funded issue
](https://github.com/gitcoinco/web/issues/1773)

**Avatar Builder**
- [ ]  [Wrong Eye Color](https://github.com/gitcoinco/web/issues/1543) 
- [ ] [Art Alignment issues](https://github.com/gitcoinco/web/issues/1523)

**Gitcoin Bot**
- [x] [Dia value wrong on Gitcoin Bot ](https://github.com/gitcoinco/web/issues/1592)  - https://github.com/gitcoinco/web/pull/1656/
- [ ] [Status changed prior to payout](https://github.com/gitcoinco/web/issues/1647)

**General**
- [x] hide metamask banner on all marketing images

**Tips**
- [x] [Logo and Profile not clickable](https://github.com/gitcoinco/web/issues/1739)

**Comment by PixelantDesign** [comment]
Moving the remaining bugs to August Bug List
