### ISSUE TITLE
== BUG LIST - AUGUST 2018 ==

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1867]
## **In Priority Order**

**Priority Guide**
**P0**  - **Critical**
This issue puts funds at risk for either a) Gitcoin funders or b) Gitcoin developers.
_Timeline to fix: 24-48 hours_
**P1**   - **High**
A feature of Gitcoin fails to follow expected behavior. The issue creates panic around a core feature on the Gitcoin platform.
_Timeline to fix: 2-3 days_
**P2**  - **Medium**
A feature of Gitcoin fails to follow expected behavior. The issue is not high magnitude.
_Timeline to fix: 5-7 days_
**P3** -  **Low**
Gitcoin’s platform is following expected behavior, but the expected behavior is resulting in sub-par user experience. 
_Timeline to fix: 1-7 days_

======================================================================

**### Please link to the PR by adding the URL next to the issue or comment on this thread so that we can tip.**

**From July**
- [x] [Users Not Receiving Tips Email Notification or Profile drop down](https://github.com/gitcoinco/web/issues/1870)
- [x] [Wrong funded time period shown](https://github.com/gitcoinco/web/issues/1774)
- [x] [Single Payout Broken](https://github.com/gitcoinco/web/issues/1859)
- [x]  [P3 Wrong Eye Color](https://github.com/gitcoinco/web/issues/1543) 
- [x] [P3 Art Alignment issues](https://github.com/gitcoinco/web/issues/1523)
- [x] [Status changed prior to payout](https://github.com/gitcoinco/web/issues/1647)

**August**
- [x] [P1 Submit Work available Before Approval](https://github.com/gitcoinco/web/issues/1951)
- [x] [P1 Navbar Menu Has Weird Overflow](https://github.com/gitcoinco/web/issues/2071)
- [x] [P1 Funder cannot accept worker](https://github.com/gitcoinco/web/issues/1985)
- [x] [P1 Gitcoin Bot Prodding Of Applied (or Passively Rejected) Workers]
(https://github.com/gitcoinco/web/issues/1982)
- [ ] [P1 Upgrade version of eth-utils](https://github.com/gitcoinco/web/issues/2126)
- [x] [P2 Small Issue with Profile Display](https://github.com/gitcoinco/web/issues/1934)
- [x] [P2 404s on Gitcoin Profile](https://github.com/gitcoinco/web/issues/1952)
- [x] [P2 Auto-Approvals: No Update of Gitcoin Activity (in Issue Details)](https://github.com/gitcoinco/web/issues/1981)
- [ ] [P2 Crowdfunding Bounties Results in Bad Activity Stream](https://github.com/gitcoinco/web/issues/1995)
- [x] [P2 Clicking Stop Work Did Not Stop Work](https://github.com/gitcoinco/web/issues/2032)
- [x] [P2 Cookie Toaster Doesnt Show in Other Languages](https://github.com/gitcoinco/web/issues/2052#issuecomment-414751513)
- [ ] [P3 Profile Doesn't Show All Bugs](https://github.com/gitcoinco/web/issues/2055)
- [ ] [P3 Wrong Bounty Value - Gitcoin Bot](https://github.com/gitcoinco/web/issues/2137)

**Comment by vs77bb** [comment]
Would it be fair to re-name this 'Bugs / Small Product Fixes'? Just added a few issues I think fit in that category which are important operationally, but don't make their way into priorities.

**Comment by nemaniarjun** [comment]
Found a Bug! 
The feed on the landing page shows `0.1 DAI` (I am guessing that is because the bounty is in DAI)
But the Issue page says `0.1 ETH`
![image](https://user-images.githubusercontent.com/15715894/43872114-a8cd3982-9b9d-11e8-8d34-c675feccee1d.png)
![image](https://user-images.githubusercontent.com/15715894/43872131-c86f0432-9b9d-11e8-9737-979c0b384dff.png)

PS: Not creating a issue on github, as I dont know if this has already been reported.

**Comment by owocki** [comment]
Thanks @nemaniarjun -- good find.

**Comment by kuhnchris** [comment]
I think all the bugs are closed - please reopen if in error!
