### ISSUE TITLE
Deploy Grants to a staging environment

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2197]
https://github.com/gitcoinco/web/tree/grants

Please deploy this to a new environment and link it in the #proj-grants

**Comment by owocki** [comment]
cc @mbeacom

**Comment by mbeacom** [comment]
### Grants QA Environment

> Tentative rollout: Friday 21 SEP 2018 EOB

#### Tasks

- [ ] Automated build/push of `grants` branch docker tags to docker hub.
- [ ] Automated rolling deployment for `grants` branch to segregated QA environment.
- [ ] Slack notification on deploy to `#proj-grants` channel in core slack community with status, env url, and revision hash.
- [ ] DB import on automated deployment completion.
- [ ] Documentation on interacting with the QA environment and retrieving valuable 💰 log data

#### Info needed

Are there any additional steps that should be performed during the deployment rollout?
Should we include error reporting (separate sentry project)?

cc @captnseagraves @owocki

**Comment by owocki** [comment]
@mbeacom this seems pretty exhaustive.. excited to see this build pipeline working!  donno if we need ALL of the above.. i'd settle for a more barebones deployment if push came to shove
