### ISSUE TITLE
[CODE] Funder Payout Reminders 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2204]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a Gitcoin User, I want to be sure that people are being paid promptly for the time they spend developing on the platform so other great developers trust the platform.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Right now, funders sometimes forget to payout bounty hunters after the work is completed. There should be ways to remind / prompt the funder to payout when it is clear that the work has been completed. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
When work is merged, there are no reminders given to the funder. 

## Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)

### Part I: Gitcoin Flow 
1. Need to look for a scenario where a) the Github issue is closed and b) there is a related PR which the Gitcoiner accomplished which is merged. If these two things are true, move to (2). 
2. A reminder e-mail is sent to the funder if the above two conditions are met for 24 hours **without payment.**
3. After three days, @gitcoinbot pings the thread reminding the funder that this issue is good for payout (one-time reminder). 
4. If it still is not paid out in 3 days, bounty is 'escalated to moderators'. 

If payment is made at any time during the process, the bounty is removed from the above flow and no future steps occur. 

### Part II: Developer 'Payout Reminder' Button 
A simple 'Send Payout Reminder' button on the Issue Details page only available to Gitcoiner who **has submitted work** for a task. 

![screen shot 2018-09-12 at 9 56 25 am](https://user-images.githubusercontent.com/23297747/45433605-2484a580-b672-11e8-8d32-094e9d93ddb1.png)
  
- [ ] Add the 'Send Payout Reminder' button here, using proper spacing and styling. 
- [ ] When button is clicked, open a modal which says "This button sends a notification to the funder to pay out the bounty. Are you sure the bounty has been completed?" 
- [ ] Ensure only one e-mail can be sent to the funder

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] The above flow is tested, implemented, and passes all tests
- [ ] A video walkthrough showing the implementation of both Part II and would be helpful 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
- Please allow 3 rounds of reviews with @thelostone-mc @PixelantDesign @SaptakS 
- Pls review before bounty, @PixelantDesign 🙂

**Comment by oogetyboogety** [comment]
@thelostone-mc @SaptakS @owocki  -
Quick question, 
Should gitcoin use set up some endpoint for Github to push a Notification with `state_change` for merging a Pull Request https://developer.github.com/v3/activity/notifications/#notification-reasons  https://developer.github.com/v3/activity/watching/

Or should gitcoin use the built-in functionality here:
https://github.com/gitcoinco/web/blob/6d37297ca9cc5a1effd9eb1317750a08d4822cb1/app/git/utils.py#L432 
in `def get_interested_actions` with `activity_event_types` as "merged"

**Comment by owocki** [comment]
I dont see any reason to use a new github endpoit; we already the email sending / github notification examples in the codebase and AFAIK those are the only two channels covered in this PR

**Comment by oogetyboogety** [comment]
@owocki Gotcha I just reread the timing part that should be the trigger to store/change the PR's state as merged. Should these all happen at one time per day, like using a Django management command? Or should it be exactly 24 hours after submission through a threaded Python Timer?

**Comment by owocki** [comment]
24 hours (ish) sounds good to me.  maybe run it once per hour?

**Comment by oogetyboogety** [comment]
@owocki Ohhhh I see so i'll make it management command to be run once every hour then. Thanks!!!

**Comment by vs77bb** [comment]
@oogetyboogety how goes it on this one?

**Comment by oogetyboogety** [comment]
@vs77bb Almost complete, should be wrapped up tonight, the only thing left to do is to write a migration script for `BountyFulfulfillment` model which fills a new field I added to the model that represents whether there is a closed status on the bounty's issue. It then fills a new field I added to the model that represents whether there is a pull request with a merged status for the issue.

**Comment by oogetyboogety** [comment]
making myself a note to add them to `/app/dashboard/helpers.py` as well

**Comment by oogetyboogety** [comment]
@vs77bb Should be wrapped up tonight

**Comment by oogetyboogety** [comment]
@vs77bb Working on review of Part I with team. Will start on review of Part II with team tomorrow.

**Comment by oogetyboogety** [comment]
@vs77bb Working on review of Part I with team. Will start on review of Part II with team tomorrow.

**Comment by oogetyboogety** [comment]
@thelostone-mc @SaptakS @owocki - actually let's use the latest pull request for this one

**Comment by oogetyboogety** [comment]
will post videos tomorrow

**Comment by vs77bb** [comment]
@oogetyboogety Would love to see the videos whenever ready! Do you have an updated ETA? Travel gets crazy after Friday, so would appreciate something by then if possible 🙂

**Comment by oogetyboogety** [comment]
@vs77bb ah yes I'll post those by tomorrow, I was struggling to get screen recorder working in Wayland so i'll start it in X and record from there

**Comment by oogetyboogety** [comment]
@vs77bb 
Part II:
[Uploading Screencast from 10-12-2018 12:.zip…]()

**Comment by vs77bb** [comment]
@oogetyboogety 

## Part I Feedback
- Mostly looks good! 
- Can we center align the 'Submit' button on the Send Payment Reminder modal?
- Instead of the button saying 'Submit', can it say 'Yes' 

## Part 2 Feedback
- I don't think the recording worked properly 🤔only seeing the command line

Thanks for providing, happy to review again ASAP alongside @PixelantDesign!

**Comment by willsputra** [comment]
@PixelantDesign for the graphics, how about our general notifications icon?

![update notification](https://user-images.githubusercontent.com/19514207/46960929-370b5800-d0d2-11e8-8dc5-957467f92ab5.jpg)

**Comment by oogetyboogety** [comment]
@vs77bb Thanks a bunch for the feedback. I'll submit the second review's PR up tonight with both @PixelantDesign and @willsputra's recommendation and by submitting another video of the command line-I think it kept splitting the resultant file into two files for some reason, so I'll reach out if I need assistance on that.

**Comment by oogetyboogety** [comment]
@willsputra / @thelostone-mc  Is this one already in Django's static images? i didn't see it at first. If not, I'll just use the graphic you provided through this process:
https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#contributing-static-assets

**Comment by oogetyboogety** [comment]
@vs77bb Interesting that it isn't already centered on yours...I just set the style to explicity centered, I think. Could you double check if the style is being correctly rendered now? It could also be the button is not inheriting certain styles in your browser.
![screenshot from 2018-10-16 06-06-23](https://user-images.githubusercontent.com/3319254/47009467-94230000-d10a-11e8-891f-8a3aaa4a46e5.png)

Thanks!

**Comment by oogetyboogety** [comment]
@PixelantDesign I should have this completed based on the additional review comments this week!

**Comment by PixelantDesign** [comment]
@oogetyboogety I'll need to re-market this if we don't hear back in 48 hrs.

**Comment by oogetyboogety** [comment]
@PixelantDesign Please check my comments on my PR. There is a change to the requirements I tagged you on. Let me try to find the link now.

**Comment by oogetyboogety** [comment]
@PixelantDesign I needed to find out if you are okay with not greying out the button, but removing it completely, as suggested by @pinkiebell . Please let me know your input. We are close to being finished, so remarketing would be fine with me, but I can continue to help if desired. But please let me know your input on the design change.

**Comment by oogetyboogety** [comment]
@PixelantDesign https://github.com/gitcoinco/web/pull/2364#discussion_r234865004

**Comment by PixelantDesign** [comment]
Sorry @oogetyboogety. If we are close, I won't re-market. I thought you may have been busy with something else.

 I looked at the screenshot you posted on the PR, what is the reasoning for removing the Send Payment Reminder button completely vs. graying out? In what instance would that happen?

**Comment by oogetyboogety** [comment]
@pixelantdesign ok so @pinkiebell acquiesced to the original requirements on the code review :-P I will let you guys hash out the details but for now I will assume the original requirements stand in order to get this one finished within the next few days.

**Comment by oogetyboogety** [comment]
@pinkiebell , can you check the PR for the changes made in reference to your last review?

Thanks!

**Comment by oogetyboogety** [comment]
@vs77bb
I'm attaching a log from Part II and a saved copy of the email for you to check!
MHTML of email: https://0bin.net/paste/jkBv6kf13SnGi7lO#uRJvJoZPuSeo1rHKgl-TwPqDYuZItjebDBDqpQV8w3U
log of command: 
https://0bin.net/paste/uv9fTtzMuV9rgjUW#-QwVbs5V5oxICvT77r3vuhm24G/7zY/Ixrn8dI+xoGI

Thanks,
oogety

**Comment by PixelantDesign** [comment]
Hi @oogetyboogety the image isn't showing up for me. Here is a screenshot
<img width="859" alt="screen shot 2019-01-23 at 1 11 14 pm" src="https://user-images.githubusercontent.com/238235/51627548-74248900-1f10-11e9-8cb3-bd79a81ad974.png">

**Comment by oogetyboogety** [comment]
@PixelantDesign Good point, fixed this now. Somehow this wasn't in my notifications. Sorry about that. 
![screenshot from 2019-02-06 18-05-26](https://user-images.githubusercontent.com/3319254/52379898-d36ab900-2a39-11e9-9f72-0adc53314ee7.png)

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 1.60000  ETH (210.77 USD @ $131.73/ETH) has been granted to @oogetyboogety for this issue from @owocki. ⚡️ 

Nice work @oogetyboogety! Your tip has automatically been deposited in the ETH address we have on file.

 * $49743.66 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
