### ISSUE TITLE
Migrate EmailEvent categories to ArrayField

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2259]
#### Why this is needed

Recently, we introduced `EmailEvent.category` to track various email event types in: https://github.com/gitcoinco/web/pull/2148

Currently, the backend logic is storing these values as `CharField` while passing a list of strings, so the end result is:

<img width="1443" alt="screen shot 2018-09-19 at 2 54 30 pm" src="https://user-images.githubusercontent.com/7315957/45832847-0b62a100-bcd1-11e8-9e6f-4e9570c7adb3.png">

We need to update the field to accept a list of `CharField` strings.

#### Tasks

- [ ] Add a new `ArrayField` with `CharField` child items to `EmailEvent` as the field: `categories`. (https://github.com/gitcoinco/web/commit/10a12c9693b0d8f7f95ff3754181f350265bc399#diff-fb1daa18ddda205c0a024b7e1cc7c631R290)
- [ ] Run `make migrations` to create the new migration in `marketing`.
- [ ] Add a manual Django migration to `app/marketing/migrations/` to migrate existing data from `EmailEvent.category` to `EmailEvent.categories`. 
  - [ ] Left trim `[` from the `category` field value.
  - [ ] Right trim `]` from the `category` field value.
  - [ ] Split `EmailEvent.category` by `,`.
  - [ ] Strip `'` from resulting strings in the list. 
  - [ ] Set the resulting list to `EmailEvent.categories` and save.
- [ ] Update all `EmailEvent.category` references to read/write to `EmailEvent.categories`.
- [ ] Remove the `EmailEvent.category` field and run: `make migrations` to create the deletion migration.
- [ ] Write a test for storing a list of strings on `EmailEvent.categories` in `marketing/tests/test_marketing_models.py` while following the same structure/style as `marketing/tests/test_marketing_models.py`
- [ ] Test updated logic and migrations locally.
- [ ] Commit your changes and raise a PR.
- [ ] No automated tests are failing on the PR.
- [ ] Submit work on the bounty.
- [ ] Get money 💰:champagne:

#### Definition of Done

- [ ] All of the above `Tasks` have been completed.
- [ ] Core team member has reviewed the pull request.
- [ ] Core team member has tested the migrations and updated logic on staging.
- [ ] PR is merged.

**Comment by kuhnchris** [comment]
This still open @mbeacom ?

**Comment by pbteja1998** [comment]
Is this issue still open? If so, I want to work on this issue.
Thanks !

**Comment by kuhnchris** [comment]
@owocki  @PixelantDesign  @mbeacom  any infos?

**Comment by owocki** [comment]
yes it is still open

**Comment by chase1745** [comment]
Hopefully this is still open, submitted a quick PR

**Comment by kuhnchris** [comment]
@thelostone-mc @owocki please check the PR!
