### ISSUE TITLE
KS Grants QA - 11.16.18

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2862]
**Index**
- [x] Implement index revamp design
- [x] Need a link to ‘Your Grants’ in nav or in user dropdown
- [ ] Need paginator instead of infinite scroll
- [x] Change ETH in Card progress bar to be DAI
- [x] Short images shorten card length. We should enforce a certain height to maintain consistency. 

**New**
- [x] It would be nice to spice up design
- [x] If goal value in DAI is 0 all views break because progress bar divides by 0, which is NaN. Need validation to ensure amount goal is greater than 0. 
- [x] Rename “title” input tag so that google doesn’t try to guess with your name
![screen shot 2018-11-16 at 2 34 49 pm](https://user-images.githubusercontent.com/22862292/48651853-feed8280-e9b9-11e8-97ab-70eb01870b66.png)
- [x] "create Grants button should be same width as form and same color as other action buttons. See "fund Grant" button for example
- [x] When the ‘waiting_room’ screen is up, the ALPHA warning banner still sitting at the bottom of the page
- [x] remove ETH from token drop down and include "any"

**What is Grants**
- [x] Introduce yourself or your team bullet appears twice
- [x] “Contribute with any ERC-20 token’ bullet says that you can pay with ETH, but you can’t

**Details/Admin**
- [x] Title input cannot handle a long title. Cuts title off after ~15-20 characters. 
- [x] Same for url, but a little longer since the link column is wider
- [x] Need to change ETH in progreess bar to DAI
- [ ] Should users be able to edit the their monthly goal?
- [x] Need to wire up updates
- [x] POST on updates fire the cancel_grant functionality on frontend. Will likely have the same issue when grant edit info is saved. I have a solution, but need to implement. 
- [x] ‘Waiting_room’ scene need to be implemented for cancel_grant functionality
- [x] Metamask check need to be implemented for cancel_grant funcitonality
- [x] Need to smooth out design when cancel_grant fired and “This grant has ended. You can find all active grants here.” is displayed.
- [x] After a user cancels their subscription, grants/deatils should no loner show them as a supporter

**Milestones**
- [x] Would be nice to spice up design
- [ ] Should we suggest people create milestones in the Grant Creation Process?
- [x] Date entered should be the deadline completion data, not the data the milestone is started. 
- [ ] The complete button should mark the milestone as completed and the actual date the milestone is marked completed with an associated github commit hash. 

**Your Grants**
- [ ] Need paginator on both supported and created tabs
- [ ] Need to implement transactions on both tabs
- [x] Need link to “your grants” either in nav or in user dropdown. Right now no way to access it.

**Details/User**
- [x] Can we make the “Cancel Your Funding” button red? Or something other than the same blue as “Fund This Grant”.
- [x] Would be nice if users could see how much they are contributing and in what token.

**Fund**
- [x] Grant logo is super huge after update to datails
- [x] Would be nice to revamp design
- [x] Need to change ETH to DAI in progress bar
- [x] Could we abstract token approval limit to “Number of Payments”? The we could just multiply the payment value by the number of payments.
- [x] Metamask check works, but has grant logo in the middle of it right now. 
- [ ] Need to check whether funer is admin and disallow contribution
- [x] need to check whether grant is active or not and allow functionality accordingly
- [x] make sure a user can only create one subscription per grant in backend. currently only stopping this by selectively showing "Fund Grant" button

**Cancel_subscription**
- [x] Metamask check works, but has grant logo in the middle of it
- [x] Cancel_subscription seems to be broken when subscription values aren’t 0. Thought i fixed this, but it might have been merged over.

**Larger build pieces**
- [ ] Integrate subminer
- [ ] Make sure transaction data flows correctly to all progress bars, transaction history in Profile, and Emails
- [ ] QA Emails
- [x] Implement Update POST Functionality
- [x] Implement Grant Info POST functionality
- [x] Cancel Subscription is broken
- [ ] We need to make sure that a user is not able to choose different variables in their subscription if the grants creator has set requirements in their contract. Mostly pertains to tokens. 

**Outstanding Questions**
- [x] What happens when a user tries to create a new grant without a profile? Where are they caught? Do we have an error screen for this?
- [ ] Is there any check for a users wallet? I can contribute to a grant and then go to try and cancel it with a different address. Which will fail. Can we validate that at all?

**Comment by thelostone-mc** [comment]
@captnseagraves title & link input both are set to width 100% but they are still input fields which prevents them from being broken up into multiple lines.

This is only when you the logged in user owns the grant. Any suggestions on how we go about this ?

**Comment by captnseagraves** [comment]
@thelostone-mc Sorry I didnt respond to this yesterday. I implemented a solution that has already been merged. I used a textarea for each to resolve the issue.

**Comment by captnseagraves** [comment]
KO QA https://github.com/gitcoinco/web/issues/2897

**Comment by thelostone-mc** [comment]
Open issues are captured here #2949
