### ISSUE TITLE
Gitcoin SEO Audit: Add Meta Tags to issue/bounty pages

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2899]
### User Story

As a Gitcoin admin I'd like the Gitcoin site `issue/bounty` pages to have metatags (content descriptors that help tell search engines what a web page is about).

### Why Is this Needed

On the SEO side, this is high impact for Gitcoin. 

### Description

[SEO Audit Google Document, Issue Bounty Pages tab](https://docs.google.com/spreadsheets/d/1k8w8PX59XISYWaRLmUwQvdsLDCiDH0jBIY08qsKpruw/edit?usp=sharing)

The description of each `issue/bounty` page should be populated within their respective "Meta Description" and title. The first 200 characters are enough for each. 

Pull the bounty title into the `<title>` tag and 2 sentences from the bounty description into the  `<meta name="description".` tag, and make note of this.  

### Current Behavior

Title and meta tag descriptions need updating for the `issue/bounty` pages.

### Expected Behavior

Title and meta tag descriptions are in the meta tags on the actual issue page, and have been pasted into the SEO Audit Google Document for `issue/bounty` pages.

### Definition of Done

- [ ] for `issue/.*` pages (from the explorer), pull the bounty title into the meta title tag (`<title>`) if not done so already
- [x] for `issue/.*` pages (from the explorer), pull the bounty description into the meta description tag (`<meta name="description"...`) if not done so already
- [x] make note of the title and meta description phrases in the SEO Audit Googlesheet, similar to the Meta Tag Recommendations tab - edit: not required anymore.

### Additional Information

Example: https://explorer.bounties.network/bounty/1799 from bounties network (hit inspect)
Example issue/bounty page from Gitcoin: https://gitcoin.co/issue/status-im/status.im/127/1738

**Comment by kuhnchris** [comment]
I assume you refer to an internal "seo document"?
Currently meta information is set (pretty much globally) in the head already:
![image](https://user-images.githubusercontent.com/761911/48827118-8b0dfa00-ed6c-11e8-8074-35ddf9a2afd0.png)
So you want to have the specific issue data added?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.35 ETH (40.76 USD @ $116.45/ETH)  attached to it as part of the Gitcoin fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/2899/1880).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $34,669.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.35 ETH (40.76 USD @ $116.45/ETH)  attached to it as part of the Gitcoin fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/2899/1880).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $34,669.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 months, 4 weeks from now.
Please review their action plans below:


**1) [divyanshsinghvi](https://gitcoin.co/profile/divyanshsinghvi) has started work.**

First I will take the text from title id and put it in header title. For the description, I would take similar steps but I will have to think how to take out the text of paragraph in it's section.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880).

**Comment by frankchen07** [comment]
@sgr0691, are you still working on this bounty? If not, then I can remove you and re-open the issue to the public. Thanks!

**Comment by frankchen07** [comment]
@sgr0691 - I'm going to remove you on the bounty - if you see this message and it's open and you want to pick it up again, feel free to hit start work again!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 month, 2 weeks from now.
Please review their action plans below:


**1) [nanspro](https://gitcoin.co/profile/nanspro) has started work.**

I am already familiar with gitcoin's frontend and issue seems pretty straightforward so will try to finish it fast!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 month, 2 weeks from now.
Please review their action plans below:


**1) [nanspro](https://gitcoin.co/profile/nanspro) has started work.**

I am already familiar with gitcoin's frontend and issue seems pretty straightforward so will try to finish it fast!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880).

**Comment by nanspro** [comment]
@frankchen07 
Meta tags such as title and description are already there in bounties page.
Ex: https://gitcoin.co/issue/Uniswap/uniswap-api/2/2125
![screenshot_2019-01-17 screenshot from 2019-01-17 02-35-42 png png image 1920 x 1080 pixels - scaled 86](https://user-images.githubusercontent.com/24641089/51210240-49e33200-1938-11e9-9504-aa91e5b8eeaf.png)
Are you suggesting to change the current format?

So the only thing left to do is update audit sheet, right?

**Comment by frankchen07** [comment]
hey @nanspro - I did a spot check on a couple and see what you mean. 

Is there any kind of automation test that can be written to ensure that they are actually all there for each and every bounty/issue page (or perhaps you already did this in order to check). 

If that is already done, then updating the audit sheet would be all that's left!

**Comment by nanspro** [comment]
`<meta name="title" content="{{ card_title }} Bug Bounty | Gitcoin">
 <meta name="description" content="{{ card_desc | truncatechars:200 }}">`
I guess you are suggesting a test where we check if they(meta tags) are present or not? This is hard-coded in `details.html` and hence every bounty page must have these tags.

There is no automation test particularly for checking if tags are present but there are tests in which we check if title and description are correct or not.

**Comment by nanspro** [comment]
@frankchen07 
Everyone doesn't need to go and check every bounty page because it is hard-coded so if it is rendered correctly on one page then it will render correctly for other bounties also (if the value of title is not same then there are test cases which will fail automatically).
We can easily write a test case by using beautiful soup and to check presence of tags but this kind of tests i have never seen much and even gitcoin doesn't have tests like that so that's why i am asking do we need a test like that.
I'll make a PR of this soon and then we can decide if we want tests like this or not !!

**Comment by nanspro** [comment]
@frankchen07  i have updated the docs and added canonical tags in `/gas` and `gas/history`

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 0.35 ETH (36.15 USD @ $103.28/ETH) has been submitted by__:

 1. [@nanspro](https://gitcoin.co/profile/nanspro)



@frankchen07 please take a look at the submitted work:
* [PR](https://github.com/gitcoinco/web/pull/3601) by @nanspro

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/2899/1880).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $53,382.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by frankchen07** [comment]
@nanspro - paid out. Let me know if you received it!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.35 ETH (38.14 USD @ $108.98/ETH)  attached to this issue has been approved & issued to @nanspro.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/2899/1880)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $53,060.18 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
