### ISSUE TITLE
Community QA - Grants -- Week of 11/26

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2949]
# Alisa QA 11/26/2019

**Must Have**
- [x] Homepage Summary - Correct spelling of dependancy ---> dependency
- [x] Homepage Summary - Once EIP1337 Link is clicked - it is not legible. Please use the light blue Gitcoin link color.

- [x] Cancel Grant - Need an interstitial modal to explain what is about to happen if they click cancel a grant. Ex: By clicking cancel, you will delete all of the information associated, etc, etc. Include any important information the user should know about their data and funds. 
This should display prior to the metamask dialog box popping up.

**Should Have**
- [x] Homepage - Summary is a little wordy. Maybe there is a better way to explain what grants is...
Will users understand what dependency tree is? 
Suggestion: Show your appreciation for maintainers by elevating their contributions or giving them core team responsibility.  

- [x] View Grants - the columns between the 3 sections are uneven as you view the page from top to bottom.

- [x] View Grants - Description needs header similar to Team

**Won't Have**
- [ ] What is grants tab seems like it should be part of the homepage or an FTUX screen to create grant, but noting this so we can fix later. 

# Alisa QA 11/30/2019

**Should Have**

- [x] Alpha Banner - Banner is difficult to read and copy is alarming.
Suggestions: 
Invert the background and font color for legibility.
Remove the word Warning and the scary copy.
Use Copy: Gitcoin Grants is in ALPHA release. Please use caution if funding at high values.

**Nice to Have**
- [ ] Create Grant Form - Project URL - Provide hint text examples on whether this could be a normal url or a GitHub url.

- [ ] Create Grant Form - Team Members - Provide hint text guidance whether this has to be a Github user name or a regular person’s name or an email address.

- [ ] IF we default the monthly sought amount to Dai, should we default to Dai for Required Token Subscription?

- [x] Fund Grant - Change Number of Periods to Number of Recurring Payments. 

- [ ] ~~If I'm the creator of a grant, I should also be able to add funding to my own grant.~~

- [ ] Getting Started with Grants - Take Me Back link and paradigm is in a weird location, recommend removing.

# Kevin QA 2018/11/28

## LIKES
* new index page is hott
* 'my grants' page is really nice design.
* in general, the CSS seems really well baked.

## MINOR STUFF
M.png)
* [x] nav dropdown on `/grants` has funny css when i'm not logged in as staff. [expected](http://bits.owocki.com/4f6bc5091f6a/Screen%20Shot%202018-11-28%20at%203.31.34%20PM.png) vs [observed](http://bits.owocki.com/d62c68aa8e13/Screen%20Shot%202018-11-28%20at%203.32.00%20PM.png)
* [x] on quickstart page, [this link](http://bits.owocki.com/4087d819bc37/Screen%20Shot%202018-11-28%20at%203.33.56%20PM.png) should go to gitcoin.co/slack (because that link can invite ppl).  the existing link is a dead end for ppl who dont have an invite.
* [ ] on grants index page, "0 Grants available on mainnet." is hardcoded. i can't see any grants available on rinkeby.
* [x] on index page can we update "Show your appreciation for maintainers in your dependency tree with a Gitcoin Grant today." to say "Show your support".
* [x] nitpick, but the logo stretches when u hover on it [screenshot](http://bits.owocki.com/23adfcaf9349/Screen%20Recording%202018-11-28%20at%2003.37%20PM.gif)
* [x] on create grants page, on the image upload, the X doesnt work [screencast](http://bits.owocki.com/c919037451ca/Screen%20Recording%202018-11-28%20at%2003.44%20PM.gif)
* [x] On the index page the search/sort functionality does not seem to be wired up.

## MAJOR
* [x] on quickstart 'start a grant' page, this text seems broken [screenshot](http://bits.owocki.com/eeba466f30e3/Screen%20Shot%202018-11-28%20at%203.35.23%20PM.png).  also "Contribute with any ERC-20 token" seems like it belongs under 'fund a grant' not start a grant
* [x] on index page.  youtube video is wrong (its an old one that has an audio defect at 0:28).  can you please update it to [this one](https://www.youtube.com/watch?v=eVgEWSPFR2o)? 
* [x] on create grant page, i was able to post [the entire script of bee movie](http://www.script-o-rama.com/movie_scripts/a1/bee-movie-script-transcript-seinfeld.html) into the description field.  perhaps we should have a character limit?

## SHOW STOPPERS
* [x] 'my grants' link shows up in the nav even if im not an admin [screenshot](http://bits.owocki.com/ff58a21817cd/Screen%20Shot%202018-11-28%20at%203.29.57%20P)
     - Feautre, not a bug. User should be able to find any grants they are supporting or are admin of.
        If they are not an admin they are shown a "You dont have any grants yet" page - KS
* [x] On the tx processing page, "Your update is being posted to the Ethereum Blockchain" is not linked to the etherscan tx, like it is on the bounty tx processing page.
* [x] On the tx processing page, I get this error [screenshot](http://bits.owocki.com/311a18a5bc91/Screen%20Shot%202018-11-28%20at%203.45.31%20PM.png) (though it looks like [the tx](https://rinkeby.etherscan.io/tx/0x00646c06dab89a7d6c3e73c87c4a740e7b9f1c14e3af5d848c9d6fb6d7359f09) did go through! ) Tx processing page seems to go on forever and grant is not created on the index.
* [x] Trying again with a 2nd deployment, and the same thing happens.  Tx processing page seems to go on forever and grant is not created on the index.

I can't QA the Grants Detail / Fund / Cancel flow because of the showstopper above.  To be continued

# KEVINS QA 2018/11/29

## MINOR

- [ ] on index page, if i do a search, it'd be nice if the 'keyword' i input showed up in the searchbar so i remember what i searched for.
- [ ] on the 'fund' page, can we please update 'number of periods' to be a select box with options "0 => 99" and a final option "unlimited", which will be set to 9999.  itd be much more usable to have a select box, as a user, because "i dont have to think".
- [ ] on the fund/create page, there are still intermittent contract errors.  how can we workaround or fix them upstream?
- [ ] https://grants.gitcoin.co/grants/profile needs a H! saying 'my Grants' or similar. it should probably be linked on the index page too.
AM.png) and seems to be stubbed (not actually dynamic)
- [x] on https://grants.gitcoin.co/grants/profile, the 'created tab' , the text says 'you aren't supporting any grants', even though i'm on the 'created' tab.
- [ ] on the "grants detail page" (https://grants.gitcoin.co/grants/2/foo-bar) it'd be great to have a custom title/desc/unfurl image for the grant.. remember people are going to be sharing their grants on social media and we want to increase the click factor

## MAJOR

- [ ] on grants/profile, the transaction history has lorem ipsum on it [screenshot](http://bits.owocki.com/e241a900e78f/Screen%20Shot%202018-11-29%20at%2011.40.04%20
- [x] updates still not posting.  theres still lorem ipsum on the updates page
- [x] for https://grants.gitcoin.co/grants/2/foo-bar , when I posted a milestone in the past, it updated the grant detail page to say "This grant has ended. You can find all active grants here.".  is this by design?  its confusing that it closed the grant just bc I posted a milestone?
- [ ] how do i view canceled / inactive grants?   there seems to be no way

## SHOWSTOPPERS

- [ ] how do i test emails?
- [x] on the 'fund' page, i get a JS error when i try to click 'contribute to grant' [screenshot](http://bits.owocki.com/c984583908e8/Screen%20Shot%202018-11-29%20at%2011.35.23%20AM.png)
- [x] i can't send a tip on this branch [screenshot](http://bits.owocki.com/7ff8aba04c02/Screen%20Shot%202018-11-29%20at%2011.47.56%20AM.png)
- [x] i can't create a bounty at [this link](https://grants.gitcoin.co/funding/new) beucase [the token list is empty](http://bits.owocki.com/b93da185b293/Screen%20Shot%202018-11-29%20at%2011.49.52%20AM.png)
- [x] i can't test kudos sending/receiving bc there are no kudos on grants.gitcoin.co

# FRANKS QA 2018/11/29

## MINOR
- [x] on funding a project, for the amount, is it intended to be able to fund a negative amount?
- [x] when inputting "Monthly amount sought in DAI", I can add a period at the end, does that affect the final amount? (e.g 450.45.)
- [x] on https://grants.gitcoin.co/slack, it says 0 online.
- [ ] difficult to cancel the search terms once we've entered one in. (enter "testing", see 1, but tough to get rid of "testing" search, I had to click on grants in the right hand corner).

## SHOWSTOPPERS
- [x] how do we test milestones on a grant? couldn't find a way to add one.
      - @willsputra This QA point is about the design on the bottom half of the grants/deatils page. 
         The edit milestones button exists but is hard to find. Also, with the updates being dynamic the 
         bottom of the page looks a bit blah. Can you take a look?
- [x] tried creating a grant twice, contract deployment happens on metamask, and then the connection times out, and the grant isn't actually made.

# Team Call QA 2018/11/13

## Fund Grant:
- [ ] unfurl image / title / desc should use the grant logo.

## Index Page:
- [ ] show NUM subscriptoins on the card

## Your Grants
- [ ] tx history is hardcoded

## Create Grant
- [ ] down the line: figure out how to handle the attack vector where user can set a very low ETH amount.

# KS QA 2018/11/16

## Index
- [x] Need paginator instead of infinite scroll

## Details Admin
- [ ] Should users be able to edit the their monthly goal?
- [ ] Need to smooth out design when cancel_grant fired and “This grant has ended. You can find all active grants here.” is displayed.

## Milestones
- [ ] Should we suggest people create milestones in the Grant Creation Process?
- [ ] The complete button should mark the milestone as completed and the actual date the milestone is marked completed with an associated github commit hash. 

## Your Grants
- [ ] Need paginator on both supported and created tabs
- [ ] Need to implement transactions on both tabs

## Fund Grant
- [x] Metamask check works, but has grant logo in the middle of it right now. 
- [x] Need to check whether funder is admin and disallow contribution
- [x] Need to check whether grant is active or not and allow functionality accordingly
- [x] Make sure a user can only create one subscription per grant in backend. currently only stopping this by selectively showing "Fund Grant" button
- [x] We need to make sure that a user is not able to choose different variables in their subscription if the grants creator has set requirements in their contract. Mostly pertains to tokens. 
- [x] When I reject approve transaction in metamask, I still see the waiting screen, I can sign the subscriptionTx and a subscription is saved on the platform. 

## New Grant
- [x] Metamask check works, but has grant logo in the middle of it right now. 

## Cancel Grant
- [x] Metamask check works, but has grant logo in the middle of it

## Larger Build Pieces
- [ ] Integrate subminer
- [ ] Make sure transaction data flows correctly to all progress bars, transaction history in Profile, and Emails
- [ ] QA Emails

##Relayer
- [ ] we'll wnant to mae sure that if a transaction fails due to insufficient funds we need to cancel or pause or put the subscription into some other state. 

# KO QA 2018/11/20

## Loading Page
- [x] Why is my 'external URL' shown on the loading page? [screenshot](http://bits.owocki.com/b7c975bb1f06/Screen%20Shot%202018-11-20%20at%2011.16.39%20AM.png)
- [ ] integrity error upon insert [screenshot](http://bits.owocki.com/68aba02543d6/Screen%20Shot%202018-11-20%20at%2011.17.22%20AM.png) - SHOWSTOPPER

**Comment by willsputra** [comment]
>Cancel Grant - Need an interstitial modal to explain what is about to happen if they click cancel a grant. Ex: By clicking cancel, you will delete all of the information associated, etc, etc. Include any important information the user should know about their data and funds.
This should display prior to the metamask dialog box popping up.

![cancel grant](https://user-images.githubusercontent.com/19514207/49172522-45f55380-f37c-11e8-940b-90cc60be8168.png)

Sketch file:
https://drive.google.com/open?id=1uusR0LUUdCkvdRk2Qe5n7D1M5or3oluv

@thelostone-mc @PixelantDesign

**Comment by thelostone-mc** [comment]
@owocki 

>  on create grant page, i was able to post the entire script of bee movie into the description field. perhaps we should have a character limit?

Hmm got a number in mind ?

> nitpick, but the logo stretches when u hover on it screenshot

Looks like the animation svg has to be redone 😅to meet the grant logo size ?
It happens in live now too

**Comment by SaptakS** [comment]
> Cancel Grant - Need an interstitial modal to explain what is about to happen if they click cancel a grant. Ex: By clicking cancel, you will delete all of the information associated, etc, etc. Include any important information the user should know about their data and funds.
This should display prior to the metamask dialog box popping up.

@thelostone-mc @willsputra https://github.com/gitcoinco/web/pull/2995
