### ISSUE TITLE
EPIC Looking for a Job on Gitcoin

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3382]
Related to #3114 

### User Story 1
[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I want to upload my resume in the onboard flow, so that Gitcoin can match me with work that matches my profile

### Why Is this Needed
[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Because people join Gitcoin to find work.  We should have their resume on file.

### Current Behavior
[comment]: # (Describe what actually happened.)
No resume upload step

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Resume upload step in onboard flow.  This form should have the following fields in it:
* I am looking for full time work. (select: part time, contract work, just bounties, etc)
* I am actively looking / not looking / passively looking.
* I am looking for companies worldwide / in specific GEO region
* My compensation expectation is *insert expectation here*

In the backend, there should be a form expose to @ceresstation where he can search by any of the above fields, and download a resume or batch of resumes.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [x] Ux this experience
- [ ] Build Front End
- [ ] Handle the S3 upload of resume (determine file limit, types, size, etc).
- [ ] Decide on geographic region data set (google map api, city, country, etc). Octavio suggest use Google Map, rate limit is extensive.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

### Metric

------------------------------------------------------------------------------------------------

### User Story 2
[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, i want a 'im looking for a job' field in onboarding, so i can signal i want a job
### Why Is this Needed
[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
gitcoin is a great place to hire, we just lack the data of whos on the market

### Current Behavior
[comment]: # (Describe what actually happened.)
Does not exist

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
User should be able to let Gitcoin know that they're looking for a job.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] In the on boarding flow determine where it makes sense to display a checkbox to capture that user is looking for a job.
- [ ] Display in profile
- [ ] In Settings display the same checkbox to indicate user is looking for a job.
- [ ] In every email that is sent, the system should remind me that i AM/AM NOT looking for a job, as of YYYY/MM/DD, so i remember to update it if it's changed.
- [ ] @frankchen07 should built a data dashboard of who's available for hire, ranked by whose done the most bounties.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by octavioamu** [comment]
we are going to link the file or upload?
is resume something more valuable than linkedin?

**Comment by PixelantDesign** [comment]
-   Ux this experience (sprint1)
-   Build Front End of resume upload (3pt)
-   Handle the S3 upload of resume (determine file limit, types, size, etc).
-   Decide on geographic region data set (google map api, city, country, etc). Octavio suggest use Google Map, rate limit is extensive.

**Comment by willsputra** [comment]
Here's how it might look like on the onboarding step:

Default
![resume-default](https://user-images.githubusercontent.com/19514207/51554766-0a28c700-1eb1-11e9-9b81-85560763b37c.png)

Resume uploaded
![resume-uploaded](https://user-images.githubusercontent.com/19514207/51554773-0f861180-1eb1-11e9-8fe5-cfd149c540e9.png)

**Comment by PixelantDesign** [comment]
@willsputra looking good! Could make the following updates?

- Smaller size drop down. It seems a little large.
- Update ordering of the fields: 
   Are you looking for work?
   What type of work?
   Looking for companies in (location) (please remove...)
   Compensation expectation (please remove ...)
   Upload Resume

What happens if I don't complete a field? 
I should also have the ability to skip this page if I don't want to answer these questions.

**Comment by PixelantDesign** [comment]
Team Estimates:
-  In the on boarding flow determine where it makes sense to display a checkbox to capture that user is looking for a job. (sprint 1)
-   Display in profile (sprint1)
-   In Settings display the same checkbox to indicate user is looking for a job. (2pts)
-   In every email that is sent, the system should remind me that i AM/AM NOT looking for a job, as of YYYY/MM/DD, so i remember to update it if it's changed. (3pt)

**Comment by willsputra** [comment]
@octavioamu made a PR on the creative repo for the sketch files
https://github.com/gitcoinco/creative/pull/32
