### ISSUE TITLE
SUBTASK #2200 BUILD Backend Inviting Specific Gitcoiners to Work

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3507]
Reference: https://github.com/gitcoinco/web/issues/2200

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Funder, I'd like the ability to invite specific Gitcoiners to work on my issue after it is funded so that I can foster continuing working relationships with people who I know and trust. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: After the 'Fund Issue' page, while the tx is posting to the blockchain, an option should be provided to send the Gitcoin Issue either a) around the Gitcoin community to top profiles which match the bounty description or b) around the interwebs (on Twitter, Slack, elsewhere) to create a viral loop bringing more dev's into Gitcoin. 

Here's a mock-up from #2038. 

![image](https://user-images.githubusercontent.com/23297747/45382370-9820a700-b5cd-11e8-9f47-0cacd76f56b1.png)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

### Current Behavior
[comment]: # (Describe what actually happened.)
There is no in-app prompting for funders to share / invite people to work on their bounty. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
In-app ways for funders to share with a) Gitcoiner's they've worked with in the past, b) Gitcoiner's who they haven't worked with in the past, but have a good reputation / good fit for the issue and c) social sharing outside of Gitcoin to the funder's community. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Update the bottom portion of the 'Transaction Processing' page into the image provided above (for .sketch files, see #2038). 
- [ ] Re-use existing type down from Tips to search users.
- [ ] This type down should also display wether you've worked with the contributor prior and on how many bounties.
- [ ] The user should be able to clear selected user out of the input field.
- [ ] Please implement and consider failure cases and messaging.
- [ ] Please ensure that the page is responsive.
- [ ] The bounty, once submitted, still should show up in the Issue Explorer as 'Open' status (even though some people have been invited).
- [ ] The invited attendees should receive an e-mail notification / Github notification (if possible) letting them know that they've been invited to work on the task. 

### Technical Approach

**Comment by owocki** [comment]
I <3 this design.  fits so neatly into the current float. 

one thing i'd ask to add to the ticket scope is that if someone is editing the form, and the tx clears, then the user is warned [before leaving the page](https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes).

**Comment by PixelantDesign** [comment]
Duplicate Subtask
