### ISSUE TITLE
SUBTASK #2390 Design Opt In to Feature Carousel on Funder Form

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3509]
### User Story

As a funder with a new bounty, I'd like a way to callout the issue that I've just posted so I can turn the project around using the best talent on Gitcoin.

Funders expect some interest on their github pages within the first 12-24 hrs and tasks to be picked up soon after that.

### Definition of Done

- [ ] A design is created to show where on the funder form the funder can opt into this feature.
- [ ] Provide a few lines of what it is in a tooltip explaining where the featured bounty shows up.
- [ ] This features should also have a price

Here is an example:
<img width="742" alt="screen shot 2019-01-11 at 11 38 00 am" src="https://user-images.githubusercontent.com/238235/51047013-878d3700-1595-11e9-9257-e052ffc8dbef.png">

**Comment by willsputra** [comment]
Sketch file here!
https://drive.google.com/open?id=1eNc02I8oKxlVCYIk7gq43Dpd6y2s10Wt
