### ISSUE TITLE
SUBTASK 3449 UX Fund Issue from Private Repo

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3578]
#3449 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

When a user submits a bounty that is closed source on the current gitcoin.co/new flow...
The system will detect that it is from a private repo.  When it detects that, it will
1. toggle on a tooltip that says "this is a private repo.   learn more about gitcoin's support for private repos, [click here](https://link/to/cms/page/describing/private/repo_support)
2. the system will set the permission type to be 'approval required'
3. the user will be prompted to give gitcoinbot access to their private codebase.  if the user follows our intstructions for doing so, we will prefill the bounty title / desc.  if not, they will be asked to enter their own bounty / title desc.
4. the bounty hunter will be given the option to NDA any applicants.  gitcoin will have many NDAs available for funders to use.  some will be available to everyone, some will be available only to specific users.  all of them can be managed via an `NDA` model in the admin, which will have the following fields: name, description, PDF_link, available_to_users.  The NDAs can also be uploaded / managed in the Gitcoin settings page, under a new tab called 'advanced'.

user presses submit.  bounty is posted as per normal.

on the bounty explorer page
1. there will be a 'private repo' tag for this bounty on it's row on the explorer page

on the bounty detail page
1. there will be a 'private repo' tag in the header for the bounty.
2. when a user applies to start work, they will have to sign an NDA.  if they do not sign the NDA, they cannot apply.
3. when a user is approved to start work, their access to a private repo will be granted (if gitcoin bot has access to manage their perms). if gitcoinbot does not have access to add/remove them, an email will be sent to the funder reminding them to add access.
4. when a user stops work, their access to a private repo will be removed (if gitcoin bot has access to manage their perms). if gitcoinbot does not have access to add/remove them, an email will be sent to the funder reminding them to remove access.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Propose a task flow based on tech approach above.
- [ ] Provide accompanying screens with annotaitons at each step based on above
- [ ] Review with Gitcoin Core team
- [ ] Provide final sketch file
- [ ] Provide a couple of minor revisions
This task is due by 2/1

**Comment by thelostone-mc** [comment]
First clarification here : 

- Would we have would have to request for more permission from the user (aka access to private repo ) when the sign in for the first time. Since we don't differentiate btwn funder/contributor, asking for permissions from private repos might get some backlash.

- Is it possible for the bot to get a read-only access to the private repo or would the gitcoin-bot get the status of collaborator by default? The gitcoin messages aren't seen by anyone else,
 a) not let gitcoin bot post anything
 a) post only reminder for contributor 
 c) post everything (like for a normal bounty)

- Adding NDA via settings / new bounty makes sense

- Users signing NDA -> applying for start work -> funder approving after validating and inviting user -> bot would [add user as collaborator ](https://developer.github.com/v3/projects/collaborators/#add-user-as-a-collaborator)

- Disable github link on issue detail page

- Upon completion -> gitcoin bot would [remove user as collaborator ](https://developer.github.com/v3/projects/collaborators/#remove-user-as-a-collaborator) and then either remove itself / ping the funder to remove it

**Comment by danlipert** [comment]
### General

 - Should there be an inactive state for the "express interest" button once the user has submitted their application for the bounty?
 - Whats the project type default? In these designs, its shown as "Cooperative", but there's no controls to set the project type in the bounty creation flow. 
 - I like the Simple flow a lot! It seems like we could start there and then easily build out the GH Auth and/or Secure flows as additional tasks so that we get some incremental wins, and can gather feedback from bounty creators. Cutting the Github integration will accelerate the release of this feature by multiple days.

### Simple
 - Should there be more of an indication that a bounty is private on the detail page beyond the change of the button text to "Express Interest"?
 - An additional modal for the final step would likely go a long way in having a succesful worker approval. I'm thinking like:
 
 > "You've approved a worker for your bounty! Next, please add the github user `githubusername` as a collaborator to the private repo. Here's instructions: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/"

### GH Auth
 - The invite can likely happen automatically for both this and the Secure flow. I believe will require some additional permissions, however.

### Secure
 - Invite only bounties / "Visibility" section seem to be a separate task. Why is this option only enabled for this flow and not the Simple or GH Auth flows? In addition, non-private bounty creators would likely appreciate this feature.

**Comment by PixelantDesign** [comment]
Adding the file here for reference:
[Private Repo UX.pdf](https://github.com/gitcoinco/web/files/2832365/Private.Repo.UX.pdf)
