### ISSUE TITLE
SUBTASK 3450 Build backend Encourage Bounty Sharing to generate URLs

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3590]
#3450 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I want to get paid to invite my friends to work on Gitcoin, so that I can get paid for referring people to bounties. Gitcoin pays $5 for each referral made. 

### Why Is this Needed
This is needed to get more well-qualified hunters to the platform for issues which aren't being solved. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

I'd like to quantify: a) how many issues aren't being solved (i.e. are currently 'Open' with 0 applicants for 7+ days) and b) see if it's worth reducing this number. 

Anecdotally (i.e. by scrolling through the Explorer), it seems like most bounties do still end up with at least one applicant. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Within 3 months, referral brings in 100 Gitcoin users monthly each with $10 in LTV. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Each Gitcoin profile has a unique referral link to refer friends to their bounty
- This link is visible whenever the user travels to a Gitcoin issue 
- If a new Gitcoin user creates a profile after coming to Gitcoin via a referral link, this is tracked.
- If a new Gitcoin user completes a bounty, a kudos or $5 referral bonus is attributed to the referring Gitcoin hunter. 

- [ ] Needs backend to generate urls for share with token and handle the optin counter in that link (if we want to count how many users get into that shared link).

- [ ] Add ManyToMany field in Bounty model linking to the profiles invited for a particular bounty.
- [ ] Provide API to send request for saving invitees
- [ ] Creating unique shareable links for bounties

### Metrics
- tracking DoD, issues that move into or out of "open" status
- Number and rate of new referrals from referral links
- DAU / MAU trends in the positive direction

**Comment by octavioamu** [comment]
we can make this referral code used in any page and having a signup page something like `https://gitcoin.co/signup?referral=octavioamu` explaining the program but also can be `https://gitcoin.co/issueURL?referral=octavioamu` or any other, if the url contains a referral we will send it to the backend to an enpoint and if is a new user we will count it.
When this new user complete his first bounty we will pay to the referral user.

**Comment by octavioamu** [comment]
Also this can be used in others places like on the onboard we can have an "invite friends" step like linkedin where we take the github followers and suggest them to invite to gitcoin
An email will be fired to the selected friends with a happy message

**Comment by PixelantDesign** [comment]
@willsputra ^
