### ISSUE TITLE
SUBTASK #3450 Build Front-End Invite to Bounty Sharing

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3626]
#3450 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I want to get paid to invite my friends to work on Gitcoin, so that I can get paid for referring people to bounties. Gitcoin pays $5 for each referral made. 

### Why Is this Needed
This is needed to get more well-qualified hunters to the platform for issues which aren't being solved. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

I'd like to quantify: a) how many issues aren't being solved (i.e. are currently 'Open' with 0 applicants for 7+ days) and b) see if it's worth reducing this number. 

Anecdotally (i.e. by scrolling through the Explorer), it seems like most bounties do still end up with at least one applicant. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Within 3 months, referral brings in 100 Gitcoin users monthly each with $10 in LTV. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Each Gitcoin profile has a unique referral link to refer friends to their bounty
- This link is visible whenever the user travels to a Gitcoin issue 
- If a new Gitcoin user creates a profile after coming to Gitcoin via a referral link, this is tracked.
- If a new Gitcoin user completes a bounty, a kudos or $5 referral bonus is attributed to the referring Gitcoin hunter. 

- [ ] Add people search type down on front-end
- [ ] Ensure that the search returns and is working properly.
- [ ] Review with @SaptakS and Green squad team

### Metrics
- tracking DoD, issues that move into or out of "open" status
- Number and rate of new referrals from referral links
- DAU / MAU trends in the positive direction
