### ISSUE TITLE
SUBTASK #2390 Design Confirmation Email 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3627]
### Design Fund Issue Success Email

If user has selected featured bounty edited the issue to included feature bounty, we need to send a confirmation email.

### Definiton of Done

- [ ] Design an email that tells funders their bounties were funded sucessefuly.
- [ ] Add a section to highlight that they've also purchased featured bounty
- [ ] Email should be responsive
- [ ] Review with green squad core team

Note: Building this email will be bountied.
cc: @thelostone-mc

**Comment by PixelantDesign** [comment]
Looks great!
@iamonuwa are you interested in building this email?

**Comment by iamonuwa** [comment]
Awesome! Let's do this!!!

**Comment by octavioamu** [comment]
Main issue #3651
