### ISSUE TITLE
SUBTASK #3449 Build Front End Private Repo

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3675]
#3449 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Full Plan**

_Build Simple Flow_
**Front End**
- [ ] Funder Form - Make funder form to support Upload NDA
- [ ] Funder Form - Add Graphic/Explaination
- [ ] Funder Form - Make Issue Details editable
- [ ] Funder Form - Block the type of Issue (from the funder form)
- [ ] Issue Explorer - Denote differently private repo issues
- [ ] Issue Explorer - Left rail filter for private repo
- [ ] Issue Details - Display Private Repo lock
- [ ] Start Work Form - Add NDA upload to start work
- [ ] Fund Issue Confirmation - Build Next Steps Screen
- [ ] Email - Send Confirmation with NDA link

**Backend**
- [ ] Upload to S3 Backend NDA (Unsigned)
- [ ] Upload to S3 Backend NDA (Signed)
- [ ] Saving the type of the issue - public vs. private
- [ ] Funder Form - Block the type of Issue (validate)
- [ ] Filter for private repo on issue explorer
- [ ] Email - Send Confirmation with NDA link

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
We will need to source the NDA copy from legal.
We will need to write a CMS page about how private repos work.

If there is a dispute, how does someone arbitrate without looking at the IP / public PR?  We will have to keep a close eye on this and handle it in a v2.

### Metric
- MPV, active funders, & bounty hunters on private repos as compared to public ones
- LTV on public repo bounties vs private repo bounties

**Comment by SaptakS** [comment]
Done in https://github.com/gitcoinco/web/pull/3728
