### ISSUE TITLE
SUBTASK #2510 WORKSHOP Verified Contributor/Funder

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3678]
#2510 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who has either funded an issue on Gitcoin or completed several bounties successfully, i'd like a 'verified' image on my profile, so ppl know i'm legit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

so that you can easily visually distinguish which users that you may potentially work with are legit

inspiration from twitter:
![twitter-verify](https://user-images.githubusercontent.com/513929/47306331-5a119c80-d5e9-11e8-8c6d-a2eda6b2cd7e.jpg)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no verification image
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
verification image

### Definition of Done

- [ ] Workshop an experience that would for for Gitcoin.
- [ ] Create a final task flow and designs for V1 of verified feature
- [ ] Review with squad & extended team

_Possible Idea from Kevin's ticket._
1. users can request to be verifid
2. email is sent to an admin asking for verfification
3. admin can check a checkbox on the profile to verify them
4. verification image shows up in their profile image, and also on their profile

### Metrics
- verified user MPV, median bounty sizes compared to not verified user MPV, median bounty sizes
- verified user bounty throughput compared to not verified bounty throughput
- subjective feedback on how contributors and funders interpret and use the verified badge
