### ISSUE TITLE
SUBTASK #3450 BUILD Frontend Sharing with Kudos

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3679]
#3450 

### User Story

As a contributor, how can I encourage other great developers to join Gitcoin and help grow open source?

### Why Is this Needed
To grow the Gitcoin platform with qualified contributors/developers. how do we best do this? 

### Problem Description

There are a lot of ways to tackle virality. How do we approach this so that we aren't having to pay as much as we would pay for google ads when our goal is to get CAC down?

### Definition of Done

_Front End_  5
- [ ] Build custom link for each person or keyword
- [ ] Display Activate link - Invite to specific bounty
- [ ] Detect when someone uses the link (send to backend)

_Backend_ 8
- [ ] Build custom link for each person or keyword
- [ ] Make Activate link work - Invite to specific bounty
- [ ] When do I send the kudos? when a bounty is paid

_Other considerations_
- [ ] where to surface the link for senders
- [ ] communicate benefits
- [ ] v2 - show count in profile

### References

[Building Content Loops]( https://firstround.com/review/pinterest-and-grubhubs-former-growth-lead-on-building-content-loops/)

### Metric

1. pure absolute number of friends who complete a bounty by those invites
2. value of Kudos given out
3. retention % of those profiles who refer and get a kudos
4. for those who joined by a friend invite, do they retain better than just organics who find Gitcoin?
