### ISSUE TITLE
SUBTASK #3449 Design What to Do Next - Private Repo

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3696]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Definition of Done

- [ ] Come up with what we should communicate to funders once they've successfully funded an issue from their private repo.
- [ ] Design a page that explains what the funder should do next.
- [ ] Review with team
- [ ] Provide final files for build

### Additional Information

Refer to the **Simple** ux flow.

### Metric
- MPV, active funders, & bounty hunters on private repos as compared to public ones
- LTV on public repo bounties vs private repo bounties

**Comment by willsputra** [comment]
(draft! still brainstorming)

What to do next:
1. You'll receive an email every time a contributor applies to your bounty. Each application should come with the contributor's details and signed NDA. You can also view the applications on the Issue Details page.
(Note: contributors will not have access to your repo unless you approve them)
2. Approve Worker to assign them to your bounty and automatically invite them to your private repo.
3. Reject Worker to automatically remove them from the bounty and your private repo.
4. Once the bounty is completed, they will automatically be removed from your private repo.

Additional:
• Share or invite contributors and get more people to your bounty
• You can also make use of Featured Bounties to get more exposure on your bounty

**Comment by willsputra** [comment]
@PixelantDesign maybe we could explain this in the bounty funded email? I wonder if we need a separate page...

![private bounty success](https://user-images.githubusercontent.com/19514207/52604422-c0c30a80-2ea5-11e9-98ca-574e7d6df6cf.png)

**Comment by PixelantDesign** [comment]
Hmm good first stab.

I like the visual direction.

I was thinking more along the lines of... with the simple flow, we’ll need to on the last screen remind the funder to allow permissions for that contributor on github outside of gitcoin. And other similar ideas.

@octaviomau

**Comment by willsputra** [comment]
Included more explanation on how the funder has to invite the contributor on GitHub

Bounty Success Email
![private bounty success](https://user-images.githubusercontent.com/19514207/52722951-9711fc80-2fe7-11e9-97d9-6b2ff7012e40.png)

Another place where it'd be good to remind the funder is when they Approve Worker. Once they click Approve Worker inside Issue Details, we could do a modal:
![approve worker](https://user-images.githubusercontent.com/19514207/52723123-e5270000-2fe7-11e9-9f50-7756609ddff1.png)
