### ISSUE TITLE
Subtask #3449 Build Front End What to Do Next Modal

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3789]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Definition of Done

**Modal  You have successfully approved a contributor for the bounty**
Screenshot to show where to go to give permission on Github - private repo settings

- [ ] Build a screen that explains what the funder should do next.
- [ ] Add appropriate tracking (discuss with team)
- [ ] Review with team

### Additional Information

Refer to the **Simple** ux flow.

### Metric
- MPV, active funders, & bounty hunters on private repos as compared to public ones
- LTV on public repo bounties vs private repo bounties

**Comment by willsputra** [comment]
![whats next modal](https://user-images.githubusercontent.com/19514207/53104889-24ff6180-356b-11e9-8654-b70316af85bc.jpg)

Sketch file: https://github.com/gitcoinco/creative/pull/37/commits/b6c4fafe15e096bbd2e7d1d44590fd71c0bfb8a9

**Comment by thelostone-mc** [comment]
@octavioamu would make sense to get the link the button in the modal -> to the settings page of the repo so that the funder can simply invite user directly

**Comment by octavioamu** [comment]
Yes is where it should go

**Comment by octavioamu** [comment]
@SaptakS I need some help with this because `?mutate_worker_action=approve&worker={worker}'` is not an ajax endpoint so I don't have a success state to prompt the modal. I see 2 ways to solve this:

1_ Change that function to work with ajax calls and return json (that will need some changes in BE and a few in FE) most correct solution but more work also
2_ Add some kind of element as "message" maybe something like "success:true" so I can add a conditional in the html and run the modal function if that is true

What do you think? there is another easy way I'm missing?

**Comment by SaptakS** [comment]
@octavioamu check the message.tags in the javascript file and if it is "success" then it means that the approval worked.

**Comment by SaptakS** [comment]
Done in https://github.com/gitcoinco/web/pull/3728
