### ISSUE TITLE
Subtask #3449 Build What To Do Next Email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3790]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Definition of Done

**_This is a front end and backend task_** 
If you are the owner, please work with the supporting engineer to complete this.

- [ ] Build an email that explains what the funder should do next.
- [ ] This should leverage successfully funded issue email template and add on the missing pieces.
- [ ] Review with team

### Additional Information

Refer to the **Simple** ux flow.

### Metric
- MPV, active funders, & bounty hunters on private repos as compared to public ones
- LTV on public repo bounties vs private repo bounties

**Comment by willsputra** [comment]
![private bounty success email](https://user-images.githubusercontent.com/19514207/53189617-ea68f800-3642-11e9-8daa-4b34a95c954f.jpg)

**Comment by SaptakS** [comment]
Done in https://github.com/gitcoinco/web/pull/3728
