### ISSUE TITLE
SUBTASK #2510 Build Front End Verified Contributor Profile Update 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3791]
#2510 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who has either funded an issue on Gitcoin or completed several bounties successfully, i'd like a 'verified' image on my profile, so ppl know i'm legit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

so that you can easily visually distinguish which users that you may potentially work with are legit

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no verification image
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
verification image

### Definition of Done

- [ ] Build Updates to Admin, show checkboxes
- [ ] Add a graphic to display the verified badge
- [ ] Update header to profile page
- [ ] Build flyout on profile page
- [ ] Link flyout to Verified Info page
- [ ] Update with leaderboard rank (nice to have)
- [ ] Set up data tracking (work with @frankchen07 
- [ ] Review with squad & extended team

_Possible Ideas for future from Kevin's ticket._
1. users can request to be verifid
2. email is sent to an admin asking for verfification
3. admin can check a checkbox on the profile to verify them
4. verification image shows up in their profile image, and also on their profile

### Metrics
- [ ] bounty metrics (median bounties completed, median bounty size, acquisition retention) cohorted by "verified status"
- [ ] subjective feedback from funders who complete bounties using verified contributors

**Comment by willsputra** [comment]
draft
![profile](https://user-images.githubusercontent.com/19514207/53107475-0e0f3e00-3570-11e9-8254-8c51abed2ad9.jpg)
