### ISSUE TITLE
Subtask #2510 Build Verified Contributor Email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3792]
#2510 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who has either funded an issue on Gitcoin or completed several bounties successfully, i'd like a 'verified' image on my profile, so ppl know i'm legit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

so that you can easily visually distinguish which users that you may potentially work with are legit

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no verification image
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
verification image

### Definition of Done

Front End
- [ ] Build front end of email to communicate that a contributor has been verified.
- [ ] Make it responsive

Backend
- [ ] Build backend of email to communicate that a contributor has been verified.
- [ ] View to render html and text emails Function to send the email to a particular user from a particular email id
- [ ] Adding a cronjob to run the management command
- [ ] Adding in the view/management command when to send the email 
- [ ] Decide what's best for performance when the email is fired, one by one or **batch daily**
- [ ] Set up data tracking (work with @frankchen07 
- [ ] Review with squad & extended team

_Possible Ideas for future from Kevin's ticket._
1. users can request to be verifid
2. email is sent to an admin asking for verfification
3. admin can check a checkbox on the profile to verify them
4. verification image shows up in their profile image, and also on their profile

### Reference
Design from @willsputra (Please add mockup here)

### Metric
TBD

**Comment by willsputra** [comment]
![verified badge email copy](https://user-images.githubusercontent.com/19514207/53108326-cbe6fc00-3571-11e9-8ea5-9271d941cc44.png)

**Comment by PixelantDesign** [comment]
@octavioamu Change More info to view profile
