### ISSUE TITLE
Subtask #2510 Build Front End Verified - Explanation Page 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3793]
#2510 

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who has either funded an issue on Gitcoin or completed several bounties successfully, i'd like a 'verified' image on my profile, so ppl know i'm legit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

so that you can easily visually distinguish which users that you may potentially work with are legit

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no verification image
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
verification image

### Definition of Done

- [ ] Build Explanation Page to verified program
- [ ] Add a subnav link to How it Works Page
- [ ] Page should be responsive
- [ ] Request to be verified - type form
- [ ] Set up data tracking (work with @frankchen07 
- [ ] Review with squad & extended team

_Possible Ideas for future from Kevin's ticket._
1. users can request to be verifid
2. email is sent to an admin asking for verfification
3. admin can check a checkbox on the profile to verify them
4. verification image shows up in their profile image, and also on their profile

### Metric
TBD

**Comment by willsputra** [comment]
![verified badge page](https://user-images.githubusercontent.com/19514207/53111931-07d18f80-3579-11e9-879c-5ee43a03c74b.jpg)

**Comment by Anish-Agnihotri** [comment]
Have the sketch file for the graphics? I'll add this in right now.

**Comment by willsputra** [comment]
@Anish-Agnihotri here's the Sketch file! :)
https://github.com/gitcoinco/creative/pull/43/commits/4d1245f1d809ea0a9b82c5b8835e262900675bae

**Comment by Anish-Agnihotri** [comment]
Will knock this out tonight.

**Comment by Anish-Agnihotri** [comment]
@willsputra

Finished the page, see PR above for additional information.

Just need the copy for the FAQ accordion, and the link to the typeform now for a merge.

**Comment by PixelantDesign** [comment]
Could we remove FAQ?

**Comment by PixelantDesign** [comment]
What questions were you thinking would go in there @willsputra ?

**Comment by Anish-Agnihotri** [comment]
Sure, I can go ahead and remove the FAQ if there is no need for that.

**Comment by willsputra** [comment]
@PixelantDesign things like:
1. What is a verified contributor?
2. How do I get verified?
3. What are the requirements to get verified?
4. What happens after I request verification?
5. What are the perks of being a verified contributor?

... or other questions that might appear in the future.

I guess most of these are explained in the page already, so we can hide it for now. We can put it back if we have more questions in the future.

**Comment by Anish-Agnihotri** [comment]
Honestly, I think some of those questions have value. Especially, `What happens after I request verification?` or `What are the perks of being a verified contributor?`

Might be potential to still have a FAQ section but simply shorten it a bit?
