### ISSUE TITLE
Document All Features of Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3806]
### As a contributor/funder I'd like a place to reference all of the features that exist on Gitcoin.

**This Bounty is for Part 1**

### Definition of Done

**Part 1**

- [ ] Document all features as outlined in [google doc](https://docs.google.com/document/d/1PNJt1-nZTZlcxiZlcVyW5aJJbMuEf20wfQVREGBHsMo/edit?usp=sharing)
- [ ] Review and make recommendations where the current content fits in https://gitcoin.co/funder-guide/#4
- [ ] Review and make recommendations where this content fits in https://gitcoin.co/developer-guide/
- [ ] Allow for a few revisions

**Part 2**
- [ ] Once content is complete, add it to Wagtail Guide that has been built here.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1.2 ETH (172.85 USD @ $144.04/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3806/2444).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/3806/2444).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $58,063.64 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks, 4 days from now.
Please review their action plans below:


**1) [krisc](https://gitcoin.co/profile/krisc) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/web/3806/2444?mutate_worker_action=approve&worker=krisc) | [reject worker](https://gitcoin.co/issue/gitcoinco/web/3806/2444?mutate_worker_action=reject&worker=krisc))_.**

I've been contributing to open source through Gitcoin since December 2018 and would love to contribute to Gitcoin itself! I think documentation would be a great start for me. I have a blog on Steemit if you want to see my writing:
https://steemit.com/@kuyakris

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3806/2444).

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by srikarmv** [comment]
Thanks for letting me access the doc. I can complete documenting all the features listed by 2 to 2.5 weeks from now. In case I'm approved for the work I will submit sample/draft documentation containing few of the topics mentioned in the doc, specifically Welcome to Gitcoin, How it Works, Issue Explorer by 3 days from the date of approval, based on which my work can be judged and it can be decided whether I should continue.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by CPSTL** [comment]
@gitcoinbot I am still working on this and speaking with the team about an update.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by owocki** [comment]
sorry, we still need to tune gitcoinbot. it shouldnt comment if youve commented in the last several days

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by owocki** [comment]
@CPSTL thoughts here?  should i close down the task?

**Comment by CPSTL** [comment]
@owocki Presenting it to @PixelantDesign in the next two days.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by CPSTL** [comment]
Part 1 of the Issue was presented to @PixelantDesign to review

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by CPSTL** [comment]
The team is reviewing the work and will be suggesting some revisions.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by CPSTL** [comment]
Working with the team to finalize the work.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by CPSTL** [comment]
Submission is in final review by the Gitcoin Core team.

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
@cpstl Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/3806/2444?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 1.2 ETH (209.61 USD @ $174.68/ETH) has been submitted by__:

 1. [@cpstl](https://gitcoin.co/profile/cpstl)



@PixelantDesign please take a look at the submitted work:
* [PR](https://paper.dropbox.com/doc/Gitcoin-Documentation--Aa6r59AVcabrrgq_JErZeEEcAQ-0Ht34nS3uiZPvSCAOGrTt) by @CPSTL

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3806/2444)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/3806/2444).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $51,623.98 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 1.2 ETH (198.34 USD @ $165.28/ETH)  attached to this issue has been approved & issued to @CPSTL.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3806/2444)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $80,918.44 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
