### ISSUE TITLE
Clean Up and Surface Leaderboard In the Top Nav

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3824]
### User Story

As a Funder I'd like to easily see who the most active/best contributors are on the Gitcoin Platform.

As a Contributor I'd like to see who the best contributors are on the Gitcoin Platform.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

- Funders feedback - they'd like to know who the quality developers are on the platform and easily see this information.
- Currently the Leaderboard is Hidden

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Definition of Done

- [ ] Review gitcoin.co/leaderboard
- [ ] Clean up the front end as shown in the design
- [ ] Pull tags under names from issues the contributor has worked on, show 3-5 recent
- [ ] Surface the page in the top navigation
- [ ] In the top nav reorder the nav items so that it reads: Issue Explorer, Leaderboard, How It Works
- [ ] The nav change and leaderboard page update should be responsive
- [ ] Review with Gitcoin Core Team members
- [ ] All PR  tests must pass prior to bounty payout

### Data Requirements
[comment]: # 
- Increase in bounties funded, median goes up
- Work quality on the platform goes up, less funder complaints
- Add click tracking to leaderboard link in the top nav
- Add tracking on profile links on leaderboard page if possible

### Additional Information
<img width="698" alt="screen shot 2019-02-22 at 6 10 30 pm" src="https://user-images.githubusercontent.com/238235/53276947-7aed1a00-36cf-11e9-9237-fdf4ece87da6.png">

**Comment by deeayeen** [comment]
### Old Leaderboard
![](https://i.imgur.com/DJsWUie.png)

### Progress
![](https://i.imgur.com/LA6q96p.jpg)

### Goal
![](https://user-images.githubusercontent.com/238235/53276947-7aed1a00-36cf-11e9-9237-fdf4ece87da6.png)
 
 ### Done
 * [x]  Review gitcoin.co/leaderboard
 * [x]  Clean up the front end as shown in the design (_need to add table headers, change body to card, add winner icon, nav active underline_)
 * [x]  Surface the page in the top navigation
 * [x]  In the top nav reorder the nav items so that it reads: Issue Explorer, Leaderboard, How It Works
 * [x]  The nav change and leaderboard page update should be responsive

### Todo
 * [ ]  Pull tags under names from issues the contributor has worked on, show 3-5 recent
 * [ ]  Review with Gitcoin Core Team members
 * [ ]  All PR  tests must pass prior to bounty payout
 
### Data Requirements
 * Increase in bounties funded, median goes up
 * Work quality on the platform goes up, less funder complaints
 * Add click tracking to leaderboard link in the top nav
 * Add tracking on profile links on leaderboard page if possible

**Comment by PixelantDesign** [comment]
ohhh exciting! cc @thelostone-mc ^

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.9 ETH (124.1 USD @ $137.89/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3824/2501).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/3824/2501).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $42,598.92 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now.
Please review their action plans below:


**1) [akintunde102](https://gitcoin.co/profile/akintunde102) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gitcoinco/web/3824/2501?mutate_worker_action=approve&worker=akintunde102) | [reject worker](https://gitcoin.co/issue/gitcoinco/web/3824/2501?mutate_worker_action=reject&worker=akintunde102))_.**

I am capable of doing this. The processes would be:
- Understanding how the HTML and CSS files work with each
- Understanding how the CSS classes, IDs and CSS frameworks (if any) work together
- Then I will start editing the CSS and HTML files to bring the specified result in the design picture provided 
- Then work on responsiveness by tweaking the grid structure and media queries a bit
-  Then review my work to see if it balances with what you want.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3824/2501).

**Comment by thelostone-mc** [comment]
@deeayeen Could you 
- apply for start work 
- make sure it's responsive
- also how are you getting the languages for the user ? me curious / is that hardcoded for now ?

**Comment by deeayeen** [comment]
@thelostone-mc 
Hey Aditya,
* I can't apply to start work due to the issue described [here](https://github.com/gitcoinco/web/issues/3869).
* I am working on making everything perfectly responsive.
* The languages are currently hardcoded as a placeholder, but I assume they can be pulled from the "TECH_KEYWORDS" field in the LeaderboardRank section of the database. The issue is that this field is not loading in locally. I will look for a solution!

**Comment by PixelantDesign** [comment]
@thelostone-mc @SaptakS @octavioamu any ideas here?

**Comment by prastut** [comment]
I see @deeayeen has made quite a lot of progress. Are you finishing up @deeayeen or is the issue still up for grabs?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 0.9 ETH (123.67 USD @ $137.41/ETH) has been submitted by__:

 1. [@deeayeen](https://gitcoin.co/profile/deeayeen)



@PixelantDesign please take a look at the submitted work:
* [PR](https://github.com/gitcoinco/web/pull/3933) by @deeayeen

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3824/2501)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/gitcoinco/web/3824/2501).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $39,466.41 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.9 ETH (147.3 USD @ $163.66/ETH)  attached to this issue has been approved & issued to @deeayeen.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/3824/2501)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $70,179.11 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
