### ISSUE TITLE
[Epic] - Ease of Use on Gitcoin

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3844]
### User Story

This ticket is to track UX changes on Gitcoin that improve the usability and UX.

### Why Is this Needed

Improving usability and UX improves the overall customer experience. 

### Description

1. Fix up design ready static marketing pages:

- [ ] results
- [ ] mission
- [ ] values
- [ ] team
- [ ] faq

2. Setting up intuitive URLs:

- [ ] keeping a single page for funders and contributors as opposed to separate 
- [ ] ensure similar url flow (e.g `gitcoin/bounties/how` and `gitcoin/grant/how`)
- [ ] gitcoin tips is not marketed well, let's expose it better

3. Existing tickets:

https://github.com/gitcoinco/web/issues/3769
https://github.com/gitcoinco/web/issues/3770
https://github.com/gitcoinco/web/issues/3771
