### ISSUE TITLE
Data Tracking for Star Ratings 1.1

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3973]
**User Story**
As a Gitcoin team we'd like to understand the data from the star ratings feature.

**Definition of Done**
- [ ] Provide recommendations on how to set up the tracking to engineering team.
- [ ] Confirm that recommendations provided are implemented and in place.
- [ ] Set up/modify meta base dashboard to support new data.
