### ISSUE TITLE
Build - Filter by Org in User Directory

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4338]
**Subtask of User Directory**

- [ ] Build front end and backend of Filter organizations
- [ ] Post screenshot or video, or staging link
- [ ] Review with team
