### ISSUE TITLE
As a Gitcoin operator, for future hackathons, I want adequate data tracking so we can cohort and get baseline metrics on how the hackathon is doing

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4586]
### User Story

As a Gitcoin operator, for future hackathons, I want adequate data tracking during the onboarding phase so we can cohort and get baseline metrics on who is participating in the hackathon, as well as which bounties were funded for the hackathon.

### Why Is this Needed

For the MSFT hackathon, onboarding and applicant tracking was done with Typeform, which isn't a scalable way to cross reference with Gitcoin's data in order to have a complete picture of which bounties were hackathon bounties, and which contributors were hackathon contributors. This way we can track who joins the hackathon, their location, their code preferences, and what bounties they have completed.

The solution to this problem has to be scalable for multiple hackathons in the future, so manual solutions involving a flow that is hackathon-specific may not be the best for engineering resources.

### Description

An easy way to knock out 90% of the data labeling is to label any hackathon bounties in the data model with a flag (or string, stating which hackathon it is from) and make sure everyone who participates in the hackathon "starts work" on bounties they want to do. This way, we can identify Gitcoin profiles and hackathon participants through the bounties that were started on by the contributor, and we don't have to worry about creating different flows to account for new and existing users. The drawback here is if groups form and work is submitted / started by only one member of the group, we miss out on the majority of the group as hackathon participants. 

Another idea would be to airdrop a hackathon participant Kudos to anyone who does enough of an action for them to be considered part of the hackathon (does browsing on the explorer count? does "signing up" count? do they have to go as far as "starting work"?)

### Current Behavior

no column in our data model stating which hackathon a contributor is from, and no flag in our data model stating if an open bounty is part of a hackathon

### Expected Behavior

tracking in our db showing that a user joined / is participating in a hackathon
tracking in our db showing which bounties are hackathon bounties

### Definition of Done
- [ ] tracking flags for bounty hunters for hackathon signups, integrated into the hackathon onboarding flow
- [ ] tracking flags for bounties for hackathons

### Data Requirements
- [ ] location / code preferences / bounty completion metrics for hackathon contributors
- [ ] hackathon bounty statuses

**Comment by PixelantDesign** [comment]
@alexvotofuture could you sync up with @frankchen07 on how you're approaching this?

**Comment by frankchen07** [comment]
closed, tracking elsewhere
