### ISSUE TITLE
Integration branch triage issues

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#474]
- [ ] theres an issue with submission emails going out / github comments still seem to go out.
- [x] gitcoinbot makes a ton of comments on existing issues... when it shouldnt ( https://github.com/gitcoinco/web/pull/407#issuecomment-366764160 )
- [x]  re-enable sync_geth 
- [x]  interest comment id > many to many transfers not working when a bounty is updated (@mbeacom working on a fix before his flight, but we will need to also migrate over the current bounties in the DB) 
- [x] status issue => bounties were moving from work started to open (probably bc a new one is created on a sync). 
- [ ] [New Error: 271 BadFunctionCallOutput: Could not decode contract function call getFulfillment return data b'' for output_types](https://rollbar.com/mbeacom/gitcoin/items/271/occurrences/38329038680/)
- [x] "start work" results in multiple comments to a github issue instead of just one that gets updated; [example](https://github.com/gitcoinco/web/issues/198#issuecomment-367497929)

# regression testing 

* [ ] test legacy bounties end to end
* [ ] test current bounties end to end

# TODOS

* [x] kevin -i will cred jason on rollbar, github, production server

# open questions

- do we want to change `current_bounty=True` architecture?  if so, when?

**Comment by owocki** [comment]
@mbeacom @jasonrhaas

**Comment by owocki** [comment]
bug report from @eswarasai 
 https://gitcoincommunity.slack.com/archives/G9A2ZDDD3/p1519063662000239

> @owocki @mbeacom — Is there any cron running something for GitHub issues status? Because this issue again says that it has funding now which was done 4 days back and also a developer has already started working on this, but it shows no record on Gitcoin. Please check GitHub issue page for clearer picture — https://gitcoin.co/funding/details?url=https://github.com/MarketProject/Dapp/issues/32&slack=1 (edited)

**Comment by owocki** [comment]
more gitcoinbot issues => https://github.com/gitcoinco/web/issues/463#issuecomment-367415406 
https://github.com/MetaMask/metamask-extension/issues/3127#issuecomment-367205284

**Comment by owocki** [comment]
i wrote some helper scripts to migrate the interests from the old bounties to the new ones http://bits.owocki.com/3G110S3X3e0t/Archive%202018-02-21%20at%209.55.20%20PM.zip

**Comment by owocki** [comment]
>  theres an issue with submission emails going out / github comments still seem to go out.

i cannot seem to reproduce this

**Comment by owocki** [comment]
a bunch more re-submissions of funded issues happened this morning at 6am....

Slack API Tester APP [6:03 AM]
new_funded_issue worth 0.02 ETH: Privide Draft Design for the Bounty Detail Page

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/479&slack=1

Slack API Tester APP [8:02 AM]
new_funded_issue worth 0.08 ETH: get Faucet Page across the finish line

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/pull/407&slack=1
new_funded_issue worth 0.02 ETH: Privide Draft Design for the Bounty Detail Page

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/479&slack=1

Slack API Tester APP [9:03 AM]
new_funded_issue worth 0.02 ETH: Privide Draft Design for the Bounty Detail Page

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/479&slack=1

Csaba Solya [9:17 AM]
joined #notif-gitcoin.

Slack API Tester APP [9:45 AM]
new_funded_issue worth 0.065 ETH: Show Left Rail Radio Filters When Appropriate

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/411&slack=1

Slack API Tester APP [10:01 AM]
new_funded_issue worth 0.02 ETH: Investigate Adding social semantics

https://gitcoin.co/funding/details?url=https://github.com/owocki/pytrader/issues/8&slack=1
new_funded_issue worth 0.04 ETH: show conv rate rate at time of posting

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/165&slack=1

**Comment by owocki** [comment]
12c88376b8b0948d645839f432183441a8ddaca8 should fix the issue with https://github.com/gitcoinco/web/pull/407#issuecomment-367708132

**Comment by owocki** [comment]
current issues im tracking now

- old_bounties in `sync_geth` management command returning None and creating a new bounty when thats just not true
- interested m2m not getting transferred over
https://github.com/Distense/distense-ui/issues/197

**Comment by jasonrhaas** [comment]
Trying to track down those two issues above.  Where can I find the error message for the `sync_geth` error?  I'm looking through the production logs trying to find it.  Also looking for the error on the second issue.  Maybe there isn't an error message?  Just trying to duplicate the problem to find a fix.

**Comment by jasonrhaas** [comment]
Created an issue for `New Error: 271 BadFunctionCallOutput: Could not decode contract function call getFulfillment return data b'' for output_types`.

I think its a red herring but will keep an eye out for it in rollbar.  

https://github.com/ethereum/web3.py/issues/185

**Comment by owocki** [comment]
i ended up fixing the above issue.. but for future endeavours, youll want to look in `/var/log/gitcoin`
