### ISSUE TITLE
UX Team Management - Milestone 1 - How does this work for funders?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4954]
# User Story

As a funder I'd like to be able to manage permissions with my team members.

# Why
- Overwhelming number of funders requesting this feature.
- Make funder workflow easier
- We can package and sell in a subscription

# Assumptions
Human - Teams will be more than two people. 
Business - If we build this funders will improve our platform experience for funders.
Tech - Team members will not share private keys with each other. We will use modified version of standard bounties v2 (we currently use v1). Payout is what we are focusing on here. Other options like management are less important (extend, cancellation - later). 

# Definitions

This experience should:

how do I add a team member?
how do I remove a team member?
how do I payout?
it's not working even though I added a team member?

Milestone I (For Context)
- The Gitcoin platform syncs repo data from Github related to collaborators and team members, mirroring their permissions model. TBD: what level of access will allow users to be added as "Issuers", who have full control, and "Approvers", who can accept submissions and issue payout.

Use Github repo level permissions to determine which other users can take action.
1:1 to github repos

Things to keep in mind (from dan):

1. Do we want to display what data is synced?
2. Do we provide any kind of override from the synced Github information? (Can we change the logo, etc)

### Definition of Done 

- [ ] How do we educate users on how the permissions model works by default (“i.e. go to Github, do XYZ, and then this other user will have access to your bounties”). 
- [ ] Work with Dan to understand how it works
- [ ] Design an experience that communicates this
- [ ] Get feedback from funders on the proposed solution

#4850

https://github.com/gitcoinco/web/issues/4756

**Comment by willsputra** [comment]
@danlipert which github permission levels are we mirroring?
user (https://help.github.com/en/articles/permission-levels-for-a-user-account-repository), or
org (https://help.github.com/en/articles/repository-permission-levels-for-an-organization)?
or it could be either one depending on the github repo?

also, brainstorming more faqs:
>how do I add a team member?
how do I remove a team member?
how do I payout?
it's not working even though I added a team member?

how do I change a team member's permission level?
is there a way for me to manually sync with github? (or is it not needed cos it automatically syncs whenever there's a change?)
how do I transfer ownership? (https://help.github.com/en/articles/transferring-a-repository)
what are the permissions of each role? (a table like github's below would help)
![Screenshot 2019-08-08 01 17 19](https://user-images.githubusercontent.com/19514207/62643320-4b2e8780-b97a-11e9-94bd-4ae4b58eb80d.png)

do add more if I missed anything!

**Comment by danlipert** [comment]
@willsputra We'll be doing both org and repo level permissions - since all of our bounties are public, we'll just use Write and Admin permissions to determine whether you have access. Syncing will happen automatically, and there will be no manual management for now. Adding and removing members just happens on Github. If you transfer ownership, it will still sync as normal I believe.

**Comment by willsputra** [comment]
@danlipert so someone with Write or Admin permissions will be able to:
• Fund issues from that repo
• Modify bounty details (name, description, extend expiration etc.)
• Approve/reject contributors
• Payout contributors

is that correct? what else can they do?

**Comment by danlipert** [comment]
@willsputra I think that sums it up correctly 👍
