### ISSUE TITLE
Team Payout - Milestone II - UX

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4956]
### User Story

As a funder I'd like to be abale to co manage payment and permission with my team.

# Why
- Overwhelming number of funders requesting this feature.
- Make funder workflow easier
- We can package and sell in a subscription

# Assumptions
Human - Teams will be more than two people. 
Business - If we build this funders will improve our platform experience for funders.
Tech - 

### What 

UX/UI work: We should show in the user’s profile what teams and repos they are listed as having access to, and who their teammates are on our platform. Also, if we add the manual overrides to what is synced from then a UI to perform these overrides will have to be created (i.e. when I’m creating a bounty, show the users who will be added by default and allow me to add/remove other users).

### Definition of Done

- [ ] ux is created to solve the above
- [ ] Show in the user's profile what teams and repos they are listed on as having access to
- [ ] Show in profile who their teammates are on our platform
- [ ] Discuss with team on use cases for overrides
- [ ] Show the users who will be added by default and allow me to add/remove users
