### ISSUE TITLE
BUILD - bounty interest model milestone I - build out basic data model

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5327]
## User Story

BUILD - bounty interest model milestone I - build out basic data model.

### Why Is this Needed

This milestone sets up the foundation for the new bounty model, which is critical for solving a multitude of UX/UI problems that have cropped up. 

### Description

This milestone will focus on building out the basic data model for the new bounty model. This includes adding additional fields (states) where necessary. The new fields are:

State:

1. This field has a strict list of choices like “Open”, “Cancelled”, “Work Started”, etc.
2. This field is used to display in the UI what the status of the bounty is, and determine how and where it should been shown in the dashboard, explorer, filtering, etc.
3. This field is also used to determine the business logic used in handling a BountyEvent

Type:

1. This field has a strict list of choices like “Traditional”, “Cooperative”, “Hackathon” and “Contest”.

### Current Behavior

no new types or states

### Expected Behavior

coded up types and states

### Definition of Done
- [ ] new states coded up
- [ ] new types coded up

### Data Requirements
- [ ] how will these new data states show up in our database? (most likely similarly, since it's just the "new" bounty model

### Additional Information

Reference: https://docs.google.com/document/d/11JB165SoaEw0GwzkzpkWgRqiyvxFr2ojpvDeY5D3650/edit#
