### ISSUE TITLE
BUILD - bounty interest model milestone III - run new bounty interest model in parallel with current bounty interest model

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5329]
### User Story

BUILD - bounty interest model milestone III - run new bounty interest model in parallel with current bounty interest model

### Why Is this Needed

We'll be running the old data bounty model and the new one in parallel and batch migrating it over in case anything goes awry. Once the new one is up and running, we can choose to deprecate the old bounty model.

### Description

To integrate the new fields and model, first we will add additional calls to create the Bounty Events in each view where the bounty interests are created, work is submitted, bounties are cancelled, expired, etc. Once that is in place and the behavior is verified, we will then add the new bounty state field and event handling function.

Once that is working in production, finally we can begin bringing over individual sections of the codebase to make use of the new data.

### Current Behavior

nothing to integrate

### Expected Behavior

integrate milestones I and II (#5327 and #5328)

### Definition of Done
- [ ] all pieces of milestone I and II are working
- [ ] existing functionality exists

### Data Requirements
- [ ] bounty model tracks all existing data like before

### Additional Information
https://docs.google.com/document/d/11JB165SoaEw0GwzkzpkWgRqiyvxFr2ojpvDeY5D3650/edit#

Finishing this step enables:

https://github.com/gitcoinco/web/issues/3782
https://github.com/gitcoinco/web/issues/5173
https://github.com/gitcoinco/web/issues/5174
https://github.com/gitcoinco/web/issues/5080
https://github.com/gitcoinco/web/issues/5102
