### ISSUE TITLE
Update Gitcoin Community Section (Wordpress Blog) 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#640]
## Task 
This is an evolution of #584... 

To grow the Gitcoin community more effectively, we'd like a vibrant Gitcoin Community section. This 
would be broken down into two parts, at least for an MVP. 

1. Gitcoin Newsletters (use [weekinethereum.com](http://www.weekinethereum.com/) as an example) 
2. Gitcoin Videos (Livestreams, Community Calls, Weekly Core Meetings) 

## Description
We've begun an MVP version of this at [archive.gitcoin.co](archive.gitcoin.co) using WordPress as a format. It is very rough. This should make this easy pickings. 

### Newsletter Section
- Ensure that the Newsletter section immediately links to the latest open newsletter (similar to how you know when you go to [weekinethereum.com](http://www.weekinethereum.com/) you'll get to the latest and greatest) 
- Include an easy, visually appealing link to sign up for the newsletter 

## Requirements
- The community section must be on-brand  
- The newsletter section must be easily linked like [weekinethereum.com](http://www.weekinethereum.com/)
- There should be easy subscription options to Slack, Twitter, and (most importantly) the newsletter) 
- Leverage social icons from email footer in Github Issue #563 
- Please provide a layout approach prior to starting coding.

## Reviewers 
@owocki @vs77bb @PixelantDesign

**Comment by owocki** [comment]
LGTM @vs77bb -- once @PixelantDesign responds we can perhaps bounty it

**Comment by mkosowsk** [comment]
@vs77bb I've discussed the Livestream with friends and a lot of them won't be able to make it but would be interested in getting a synopsis of the Livestream after the fact with a quick write-up. Think that could either be just the Google doc Agenda with a few additions written up, and could deliver a lot of value to the community!

Would that be part of this bounty or is it out of scope?

**Comment by mbeacom** [comment]
Are there any plans to ultimately port this over to the main web application or are we sticking with Wordpress?

**Comment by owocki** [comment]
> Are there any plans to ultimately port this over to the main web application or are we sticking with Wordpress?

i know there are ongoing conversations about a static content generator..  might be worth folding them into that.  personally i dont really care for migrating wordpress to something else..  its easy to keep the content updated, and anyone we hire to do content will know it.  if you keep it updated and disable XML-RPC to reduce security surface area... it does the job fine.

> @vs77bb I've discussed the Livestream with friends and a lot of them won't be able to make it but would be interested in getting a synopsis of the Livestream after the fact with a quick write-up. Think that could either be just the Google doc Agenda with a few additions written up, and could deliver a lot of value to the community!

we def need to be better about timestamping the livestream and/or synopsising it

**Comment by mkosowsk** [comment]
@owocki If @vs77bb has the Livestream Agenda Google doc created for the Agenda, I can take notes for that in real time a la a court reporter. 

We can then share this doc with the parties that demo'd their stuff to make any comments/corrections to the notes (would aim to do this same day) and then push that out on the following Monday.

**Comment by mbeacom** [comment]
@owocki 
> i know there are ongoing conversations about a static content generator.. 
Yeah, I can see how something like Hugo would make sense in this case. My main concern is adding another service to maintain outside of the standard application.  If we're taking the time to create a Wordpress template, maybe we should consider a unified static generation template that we can reuse or extend with an SSG, so it's not a matter of updating and maintaining two templates (potentially three, if we move forward with SSG for some static views).

**Comment by owocki** [comment]
one other consideration to add about wordpress: it makes it very simple to turn gitcoin.co/community into a video podcast..  i submitted our podcast to apple on friday night so ill be curious to see if that gets accepted as is

**Comment by owocki** [comment]
podcast got accepted => https://gitcoin.co/podcast

**Comment by owocki** [comment]
> My main concern is adding another service to maintain outside of the standard application.

its probably worth having a larger convo about whether we want to move to microservices eventually or be a monolith forever.  in the former case its cheap to maintain another service, in the latter its a pain in the butt

> if we're taking the time to create a Wordpress template

my hope was that we could be pretty minimalistic with changes to the current template at https://archive.gitcoin.co (or choose another template that's pre-baked that's close enough that only requires minor changes).

@vs77bb not sure how much effort we wanted to put into making this resource super on brand or not.  perhaps you can comment on this

**Comment by owocki** [comment]
@vs77bb @mbeacom next time we're back we shoudl discuss how to move this fwd

**Comment by owocki** [comment]
@vs77bb i'm looking to bounty a few things today.. is this a good candidate? seems like we resolved the above conversation...

**Comment by gitcoinbot** [comment]
__This issue now has a funding of 0.1 ETH (64.5 USD @ $645.03/ETH) attached to it.__

 * If you would like to work on this issue you can claim it [here](https://gitcoin.co/issue/gitcoinco/web/640).
 * If you've completed this issue and want to claim the bounty you can do so [here](https://gitcoin.co/issue/gitcoinco/web/640)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $6380.25 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.1 ETH (64.5 USD @ $645.03/ETH) funding by__: 
 1. [@phoniks](https://gitcoin.co/profile/phoniks) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@vs77bb) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/640)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $6347.99 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by vs77bb** [comment]
I manually removed the bounty hunter for inactivity and have returned this to an 'Open' status! Contributions welcome 😄

**Comment by vikaskyadav** [comment]
Can anybody tell me what this line implies?
["Ensure that the Newsletter section immediately links to the latest open newsletter (similar to how you know when you go to weekinethereum.com you'll get to the latest and greatest)"](url)

**Comment by mkosowsk** [comment]
@vikaskyadav if you go to today http://www.weekinethereum.com/ you will see the April 26, 2018 edition of Week in Ethereum already opened.

All the way at the bottom are all the old editions which you still have access to, but when you go to the main page you automatically see the newest one 👍🏻

**Comment by owocki** [comment]
@vs77bb

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@jaswalt](https://gitcoin.co/profile/jaswalt) 

 has committed to working on this project to be completed 11 months, 3 weeks from now.


__Please answer following questions/comments__ @vs77bb:

First project

**Comment by vs77bb** [comment]
@jaswalt @photienao Are you planning on working this issue?

**Comment by vs77bb** [comment]
If not, @vikaskyadav does this look interesting to you? @mkosowsk's response accurately conveys what I meant with:

>"Ensure that the Newsletter section immediately links to the latest open newsletter (similar to how you know when you go to weekinethereum.com you'll get to the latest and greatest)"

**Comment by vikaskyadav** [comment]
I can try this. Just need a little guideline.

**Comment by gitcoinbot** [comment]
@jaswalt Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] auto removal (6 days)

**Comment by vs77bb** [comment]
@vikaskyadav Hit me up on [Gitcoin Slack](gitcoin.co/slack) and we can discuss if you're down to try it out. Click 'Start Work' to claim, if so!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@vikaskyadav](https://gitcoin.co/profile/vikaskyadav) 

 has committed to working on this project to be completed 11 months, 2 weeks from now.


__Please answer following questions/comments__ @vs77bb:

I have already started working on this issue. @vsbb, i will be needing your help w.r.t. the design

**Comment by gitcoinbot** [comment]
@vikaskyadav Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=100)

**Comment by vikaskyadav** [comment]
oh yeah. I am working exclusively on this issue for now.

**Comment by photienao** [comment]
yes , i'm working it

**Comment by mbeacom** [comment]
Feel free to open a PR with your progress.  Let me know if there is anything I can provide you with to get this across the finish line!

Thanks

**Comment by vs77bb** [comment]
@photienao for now, we have @vikaskyadav as working on this bounty. Just an FYI as I noticed you commented.

**Comment by gitcoinbot** [comment]
@vikaskyadav Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=1) | [3 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=3) | [5 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=5) | [10 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=10) | [100 days](https://gitcoin.co/issue/gitcoinco/web/640/293?snooze=100)

**Comment by vikaskyadav** [comment]
still working. You can check on archive.gitcoin.co. Let me know feedback on it.

**Comment by vikaskyadav** [comment]
@vs77bb @owocki  have made changes to show latest post on the main page and the link to the recent posts on the Right sidebar. I think what was required in the task is done. Could anyone please check? gotta close this one now.

**Comment by owocki** [comment]
@vs77bb ^^

**Comment by weberV** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/640/293).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $4,789.89 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by vikaskyadav** [comment]
I hope this is because of running some bad script. @weberV

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.1 ETH (57.28 USD @ $572.77/ETH) attached to this issue has been approved & issued to @vikaskyadav.__  

 * Learn more at [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gitcoinco/web/640/293)
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $11,082.18 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
