### ISSUE TITLE
issue funder should be able to stop work

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#666]
# what

an issue funder should be able to stop work for any of the parties who've started work on their bounty

i've started a WIP PR at https://github.com/gitcoinco/web/pull/665 to handle this. but have not finished it yet.

this is a bounty to finish up that PR.

## todos

* [x] data layer / logic for adding buttons to frontend
* [ ] style frontend buttons
* [ ] connect frontend buttons to backend to actually allow funder to stop work on backend
* [ ] send an email to the party that has started work letting them know the funder has removed their work

Screenshot of the work that's been done so far:
<img width="606" alt="screen shot 2018-03-19 at 11 14 42 pm" src="https://user-images.githubusercontent.com/513929/37637087-62b805d6-2bcb-11e8-99a0-d2c4261c178a.png">

**Comment by gitcoinbot** [comment]
__This issue now has a funding of 0.15 ETH (80.65 USD @ $537.64/ETH) attached to it.__

 * If you would like to work on this issue you can claim it [here](https://gitcoin.co/issue/gitcoinco/web/666).
 * If you've completed this issue and want to claim the bounty you can do so [here](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $3099.74 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.15 ETH (79.87 USD @ $532.44/ETH) funding by__: 
 1. [@kziemianek](https://gitcoin.co/profile/kziemianek) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@owocki) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $3069.77 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.15 ETH (83.46 USD @ $556.39/ETH) funding by__: 
 1. [@kziemianek](https://gitcoin.co/profile/kziemianek) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@owocki) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $3569.56 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.15 ETH (83.46 USD @ $556.39/ETH) funding by__: 
 1. [@kziemianek](https://gitcoin.co/profile/kziemianek) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@owocki) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $3502.79 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by kziemianek** [comment]
I'll push changes in a couple of days.

**Comment by kziemianek** [comment]
Prepared in #675

**Comment by gitcoinbot** [comment]
__Work for 0.15 ETH (70.72 USD @ $471.48/ETH) has been submitted by__: 
 1. [@kziemianek](https://gitcoin.co/profile/kziemianek) 

 Submitters, please leave a comment to let the funder (@owocki) (and the other parties involved) that you've submitted you work.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $2645.93 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by kziemianek** [comment]
@owocki submitted work in #675 but not referenced this issue directly.

**Comment by gitcoinbot** [comment]
__The funding of 0.15 ETH (56.15 USD @ $374.31/ETH) attached to this issue has been approved & issued to @kziemianek.__  

 * Learn more at [on the gitcoin issue page](https://gitcoin.co/issue/gitcoinco/web/666)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $2219.3 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by weberV** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This issue now has a funding of 0.15 ETH (103.82 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/666/170).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $2,014.06 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
