### ISSUE TITLE
KYC Epic

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7102]
### User Story

As a hackathon sponsor/funder on Gitcoin, I'd like to  have all of the necessary information about a developer so that I can feel good  about paying them out.

As a developer on Gitcoin, I'd like for Gitcoin to have all of my info so that there are no friction points to knowing who I am or getting paid  through the platform.

### Why Is this Needed

If we implemented KYC,  then our customers wouldn't have to worry about capturing the necessary information about a  developer, we would have everything our system that verifies the person's identity for them.

Customers have asked for this

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
No KYC

### Expected Behavior

- [ ] User has the ability to get themselves as verified 
- [ ] Enable Auto Verification PassBase. Define flow on how admin would interact for scenarios where KYC failed (emailing/etc)
- [ ] Ensure only reference to PassBase record + KYC status is stored in our DB and no sensitive info 
- [ ] KYC module should be reusable which could be wrapped around any feature with a few lines of integration
- [ ] Cronjob to periodically to sync with passbase (to avoid making calls everytime to passbase)

^ Before coding -> sync with @thelostone-mc who has a design + code laid addressing all those mentioned above

- [ ] Figure out how to geo-fence user to ensure KYC is shown to only certain users

### Definition of Done

- [ ] How would we surface his to the user
- [ ] How would we wrap this around a feature (UI)?
- [ ] What confirmations do we need to send?

- [ ] How does work in relation to grants
- [ ] How does this work in relation to tips?

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
See video demo of  passable KYC prototype that @thelostone-mc put together.
https://share.vidyard.com/watch/CvDeMUpTJjzDvUjxGXbCid

**Comment by walidmujahid** [comment]
Is this really a good option? 

Personally, I do not understand why this is being suggested for hackathon sponsors as opposed to grants. Would this not solve a lot of sybil concerns @owocki ?

When it comes to hackathons, should not the best entry be the determinate? However, the hackathon sponsors decide judging, why woulud developer details be needed?

Furthermore, while I personally would not have much of an issue giving Gitcoin identifying information, is KYC as implemented elsewhere or generally understood in line with web3 principles and Gitcoins mission as it pertains to the open source community?

If this is truly nessecary, then perhaps a web3 solution exists or could be made that would satisfy hackathon sponsors, and even bounty sponsors and grant funders that would involve Gitcoin having all info on an individual to avoid friction points.
