### ISSUE TITLE
Pre Hackathon Dev Experience Epic Week 0

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7111]
### User Story

As operators of Gitcoin hackathon, we'd like to get hackers excited in  preparation for the hackathon start.

### Why Is this Needed

Engage hackers

### Description

Feaeture

### Current Behavior
Not enough happening

### Expected Behavior
Engage hackers through ops or product

### Definition of Done

- [ ] Explore ideas on how to engage hackers
- [ ] [Idea board (sponsors)](https://github.com/gitcoinco/web/issues/6712)
- [ ] Idea bounty (hackers)  populate 20+ project ideas in advance of the event? is this going  to conflict with pitch? maybe submit private ideas to gitcoin core team?
- [ ] Create hype around company memes

### Data Requirements
# of hackers who register
