### ISSUE TITLE
Hackathon Onboarding Epic

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7119]
### User Story

As a Hacker I'd like an easy onboarding into the hackathon.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: If we update the onboarding page to be more exciting then more potential and interested hackers might register, the hackathon would get more submissions leading to sponsors will end up with great projects.

Hackathon Onboarding  Improvements
- [ ] [What do  we do to  encourage hacker participation?](https://github.com/gitcoinco/web/issues/7111)
- [x] [Add entry point to get into hackathons](https://github.com/gitcoinco/web/issues/6870)
- [x] [Update Hackathon List  Page](https://github.com/gitcoinco/web/issues/7096) @walidmujahid 
- [x] Completed Registration flow

### Current Behavior
Current onboarding page fr Q1

### Expected Behavior
Jazzed up Onboarding that  gets   hackers excited , get people to the right places

### Definition of Done

- [ ] Above its implemented

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information

How do we improve:
1) time to value, making it easy for someone to jump into a hackathon
2) quality of content on town square and smooth UX across site

#7113
