### ISSUE TITLE
Support Categories/ Interests in the system Epic

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7141]
### User Story

As an operator of Gitcoin, we'd like to know and collect developer interests so that we can surface relevant information and experience to support their interests.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:  no categorization 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: feature

### Current Behavior
doesn't exist

### Definition of Done

- [ ] design a flow for places in the app to capture this information
- [ ] design a flow to where a user might manage their interests
- [ ] design where sponsors/devs might see interests would display (user directory, etc)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
Related

As a developer on  Gitcoin, I'd like to see relevant information to me and my interests as a developer.

As a funder/sponsor on  Gitcoin, I'd like to know which developers fit in various categories, in particular which developers fit into the category my dapp falls in.

**Comment by thelostone-mc** [comment]
Is there a document i can check out where we have things like 

- User flow
- What kind of questions (I'm assuming we have this already)
- How would we leverage that info (aka a ticket + rough idea on what we'd do with this )

**Comment by PixelantDesign** [comment]
Agreement:
-  Categories are being captured for hack registration
- Incorporate categories this into normal system onboarding  per conversation this morning @octavioamu 
- UX - Figure  out where to display interests and update interests

**Comment by PixelantDesign** [comment]
Depends what happens with onboarding 

<img width="1451" alt="Screen Shot 2020-08-10 at 9 19 38 AM" src="https://user-images.githubusercontent.com/238235/89786905-a98cc980-daea-11ea-93ad-9d0b48bae38f.png">

**Comment by PixelantDesign** [comment]
Where does this fit in, in general onboarding?

**Comment by PixelantDesign** [comment]
closing since onboard handles this
