### ISSUE TITLE
Gitcoin Grants Deploy Checklist

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7372]
deploy actions (monday)
- [x] setup brightid calendar entries => https://docs.google.com/document/d/1wzPrlYu6K4R_lOcpYetU_52u4yrcozzBFVrEWjschnw/edit?usp=sharing
- [x] review zoek pr / get that working
- [x] setup image headers on grants pages
- [ ] publish 'its deployed if u want to test; heres how to submit bugs' tweet

testing
- [ ] test L1 checkout
- [ ] test zksync checkout (you have a balance)
- [ ] test zksync checkout (you DONT have a balance)
- [ ] test zksync checkout (you DONT have a balance + you close the page before the deposit finishes)
- [ ] test ETH vs DAI
- [ ] test tx validator
- [ ] test multiple web3 wallets
- [ ] test mobile checkout with status

production grants bugs to fix
- [x] https://github.com/gitcoinco/web/issues/7345
- [x] https://github.com/gitcoinco/web/issues/7319
- [x] https://github.com/gitcoinco/web/issues/7223
- [ ] migrate taxonomies

9am Tuesday
- [ ] publish launch blog post
- [ ] post a collection
- [ ] grants header uplaod

other/housekeeping
- [ ] enter grants funding info https://docs.google.com/spreadsheets/d/1HcM8PsMyBLPN6QNOMnVlwLo-1Y9vNVsfp-aI3IuDveE/edit#gid=214684567
- [ ] two emails per grant, this is lame.  srsly lets just fix this befor ethe round starts https://github.com/gitcoinco/web/issues/7131
- [ ] re-record WTF is QF and send to jon
- [ ] grants mgmt command TODO-SELF-SERVICE

later in the week
- [ ] grants governance PR (kevin)
- [ ] grants collections PR (zoek)
     + fund a collection (kevin)

kevins watch list
- [ ] grants other funding/finance info PR
- [x] add all to cart

**Comment by adamstallard** [comment]
> setup brightid calendar entries => https://docs.google.com/document/d/1wzPrlYu6K4R_lOcpYetU_52u4yrcozzBFVrEWjschnw/edit?usp=sharing


**Question:**
Can the list items have end times?

**Comment:**
Both airmeet and zoom links have "add to calendar" options for several calendar types, so we can link directly to their registration pages. Discord doesn't, but it's also "always open."
