### ISSUE TITLE
grants/crosschain - Filecoin

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#8194]
### Description

Frontend
- [ ] Add chain to grant creation form (staff flag)
- [ ] Add changes to ensure grant detail page renders right
- [ ] Set default amount and currency while adding to cart
- [ ] Build out the cart checkout flow 
- [ ] Ensure tab is shown only if grants are visible 

Backend
- [ ] Make changes to `/v1/contribute` endpoint 
- [ ] Add in chain sync logic
- [ ] Update cron to rety pending txn

**Comment by frankchen07** [comment]
closing this, duplicated here: https://github.com/gitcoinco/web/issues/8326
