### ISSUE TITLE
gpg - grants/crosschain/binance - ARCHIVED

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8280]
### Description

Frontend
- [ ] Add chain to grant creation form (staff flag) (#8281)
- [ ] Add changes to ensure grant detail page renders right (#8282)
- [ ] Set default amount and currency while adding to cart (#8283)
- [ ] Build out the cart checkout flow (#8284)
- [ ] Ensure tab is shown only if grants are visible (#8282)

Backend
- [ ] Make changes to `/v1/contribute` endpoint (#8286)
- [ ] Add in chain sync logic (#8285)
- [ ] Update cron to rety pending txn (#8287)
