### ISSUE TITLE
gpg - grants/crosschain/binance

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8288]
### Who

Binance and Gitcoin

### What

are integrating Binance into the Grants product

### Why

so grant owners can receive grant funds in Binance tokens.

### Description

Frontend
- [x] Add chain to grant creation form (staff flag) (#8281)
- [x] Add changes to ensure grant detail page renders right (#8282)
- [x] Set default amount and currency while adding to cart (#8283)
- [x] Build out the cart checkout flow (#8284)
- [ ] Ensure tab is shown only if grants are visible (#8282)

Backend
- [x] Make changes to `/v1/contribute` endpoint (#8286)
- [x] Add in chain sync logic (#8285)
- [x] Update cron to rety pending txn (#8287)
