### ISSUE TITLE
gpg - crosschain/edgeware

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8317]
#### Frontend
- [ ] Add chain to bounty creation + hack form form (staff flag)
- [ ] Funder should be able to create bounty with edgeware
- [ ] User should be able to start / stop / submit work with edgeware
- [ ] Funder should be able to payout using web3

#### Backend
- [ ] Make changes to `/v1/contribute` endpoint
- [ ] Add in chain sync logic
- [ ] Update cron to rety pending txn
- [ ] testing

## Specific Deadlines

Verifiable: TBD
Staff Flag Testing: TBD
Client Demo: TBD
Release Date: TBD
