### ISSUE TITLE
gpg - crosschain/rsk

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8318]
### Who

I'm a Gitcoin core team member

### What

helping other chains integrate with Gitcoin Bounties & Grants

### Why

so they can experience the benefits of our stacked events, and get access to our great community and reward them the way they want.

#### Frontend
- [x] Add chain to bounty creation + hack form form (staff flag) (https://github.com/gitcoinco/web/issues/8349)
- [x]  Funder should be able to create bounty with RSK (https://github.com/gitcoinco/web/issues/8350)
- [x] User should be able to start / stop / submit work with RSK address (https://github.com/gitcoinco/web/issues/8350)
- [ ] Funder should be able to payout using web3 (https://github.com/gitcoinco/web/issues/8350)

#### Backend
- [x] Make changes to `/v1/contribute` endpoint ((https://github.com/gitcoinco/web/issues/8351)
- [x] Add in chain sync logic ((https://github.com/gitcoinco/web/issues/8351)
- [x] Update cron to rety pending txn ((https://github.com/gitcoinco/web/issues/8351)

- [ ] testing (https://github.com/gitcoinco/web/issues/8352)

Tokens to be integrated

- [x] RBTC
- [ ] RDOC
- [ ] DOC

### Grants

PENDING

### Bounties
Verifiable: mid-february
Staff Flag Testing: early march
Client Demo: early march
Release Date: mid-march

### Grants
Verifiable:
Staff Flag Testing:
Client Demo:
Release Date:
