### ISSUE TITLE
g9 checklist after deploy

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#8491]
#### Description 
- [x] ensure GrantCLR are created + amounts are verified
- [x] turn on all Grant CLRs
- [x] hide all other GrantTypes (like filecoin , apollo, etc)
- [x] ensure banners are uploaded (all kinds of banners)
- [x] run the cache command
