### ISSUE TITLE
QL checklist

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#8781]
## Quadratic Lands 

🔨  -> WIP
⚒️  -> Dev Complete
✅  -> Complete

- [x] new landing page is live 
- [x] JTBD is live -  ⚒️ 
- [x] New Navbar -> allowing folks to focus attention on quadratic lands - 🔨 
- [ ] Implementing DDOS protection - cloudflare
- [ ] Merge QL code into master - 🔨 
- [x] Github login issue [ THIS IS POSSIBLE MAJOR BLOCKER ]

# Not engineering 
- [ ] onboarding email campaigns // not engineering 

# Grants Related

- [ ] Adding PoPP is a requirement
- [x] merge the pending anti sybil stuff ⚒️ 
- [ ] grants API enabled so we can fulfill vitaliks ask to decouple the protocol from the app, gas-minizmied payouts, probably 1-3 other things) (This is scopelift)
- [ ] dai matching round support

**Comment by owocki** [comment]
whats the "Github login issue"?

**Comment by gdixon** [comment]
@owocki I believe this is related to the OAuth Application API deprecation notice - github is no longer supporting access tokens supplied in the URL. 

@chibie has done some awesome work to get us updated 🙌  The deprecated endpoints were removed on May 5th, and we got the patch in here: #8800
